import { useEffect,useState } from "react";
import type { Activity, MatchingPair, PairSide } from "./default-activity";
import ActivitySettings from "./ActivitySettings";
import ActivityLeaderboard, { type LeaderboardRow } from "./ActivityLeaderboard";
import ActivityAnswerKey from "./ActivityAnswerKey";
import FocusBlurGuard from "./FocusBlurGuard";
import EditorContentHeader from "./EditorContentHeader";
import EditorImagePicker from "./EditorImagePicker";
import EditorItemActions from "./EditorItemActions";
import EditorWorkflow from "./EditorWorkflow";
import { apiRequest, forgetTeacherKey, getTeacherKey, rememberTeacherKey, supportsActivityKind, saveActivityAvailability, getStudentSession, saveStudentSession, clearStudentSession } from "./gas-client";
import "./card-game.css";
import PasswordField from "./PasswordField";

type Kind="flashcards"|"memory";
type Props={kind:Kind};
type Side="left"|"right";
type Student={paternalSurname:string;maternalSurname:string;givenNames:string};
type Card={id:string;pairId:string;side:Side;content:PairSide;open:boolean;matched:boolean};
type Score={correct:number;total:number;grade:number;elapsedSeconds:number;remainingSeconds:number|null;timedOut:boolean;attemptsRemaining:number|null};
const makePair=(n:number):MatchingPair=>({id:"card-"+crypto.randomUUID(),left:{text:""},right:{text:""}});
const empty=(kind:Kind):Activity=>({id:"",kind,title:"",instructions:kind==="memory"?"Encuentra las dos tarjetas que forman cada pareja.":"Voltea cada tarjeta y repasa su contenido.",timerMode:"none",timeLimitSeconds:180,maxAttempts:3,imageUrl:"",labels:[],pairs:[makePair(1),makePair(2)],shuffle:true,sound:true,scoring:true});
const fmt=(v:number)=>{const n=Math.max(0,Math.floor(v));return Math.floor(n/60)+":"+String(n%60).padStart(2,"0")};
function shuffle<T>(items:T[]){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function SideView({side}:{side:PairSide}){return <>{(side.imageData||side.imageUrl)&&<img src={side.imageData||side.imageUrl||""} alt=""/>}{side.text&&<span>{side.text}</span>}</>}
export default function CardGame({kind}:Props){
 const previewMode=new URLSearchParams(location.search).get("vista")==="docente";
 const [screen,S]=useState("loading"),[activity,A]=useState<Activity>(()=>empty(kind)),[draft,Draft]=useState<Activity>(()=>empty(kind));
 const [key,K]=useState(getTeacherKey()),[keyDraft,KD]=useState(""),[activities,Acts]=useState<Activity[]>([]);
 const [student,St]=useState<Student|null>(()=>{const saved=getStudentSession()?.student;return saved?{paternalSurname:saved.paternalSurname,maternalSurname:saved.maternalSurname,givenNames:saved.givenNames}:null}),[token,T]=useState(()=>getStudentSession()?.token||""),[login,L]=useState({username:"",password:""});
 const [busy,B]=useState(false),[notice,Msg]=useState(""),[seconds,Sec]=useState(0),[remaining,Rem]=useState<number|null>(null),[attempts,Att]=useState<number|null>(null);
 const [score,Sc]=useState<Score|null>(null),[timedOut,TO]=useState(false),[answers,Ans]=useState<Record<string,string>>({}),[leaderboard,LB]=useState<LeaderboardRow[]>([]);
 const [deck,Deck]=useState<Card[]>([]),[playPairs,PlayPairs]=useState<MatchingPair[]>([]),[first,F]=useState<number|null>(null),[flashIndex,FI]=useState(0),[flipped,Flip]=useState(false),[muted,Muted]=useState(false);
 const title=kind==="memory"?"Memorama":"Tarjetas";
 const total=activity.pairs?.length||0;

 async function list(keyValue:string){const r=await apiRequest("/api/teacher/activities",{headers:{"x-teacher-key":keyValue}}),data=await r.json();if(!r.ok||!Array.isArray(data))throw Error(data.error||"No se pudo verificar el acceso.");const rows=(data as Activity[]).filter(a=>a.kind===kind);Acts(rows);return rows}
 async function openSaved(savedId:string){const r=await apiRequest("/api/activity?id="+encodeURIComponent(savedId)),data=await r.json();if(!r.ok)throw Error(data.error||"No se encontró la actividad.");A(data);Draft({...data,pairs:(data.pairs||[]).map((p:MatchingPair)=>({...p,left:{...p.left},right:{...p.right}}))});return data as Activity}
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get("modo")==="maestro"){const saved=getTeacherKey();if(!saved){S("teacher-key");return}K(saved);const savedId=q.get("actividad");if(!savedId&&q.get("nueva")==="1"){A(empty(kind));Draft(empty(kind));S("teacher");void supportsActivityKind(kind).then(ok=>{if(!ok){Msg("El editor está listo, pero Apps Script necesita actualizarse para guardar esta plantilla.");return}return list(saved)}).catch(e=>Msg(e instanceof Error?e.message:"No se pudo actualizar la lista de actividades."));return}void supportsActivityKind(kind).then(ok=>{if(!ok){Msg("Actualiza el Apps Script existente con el archivo Code.gs de la plataforma.");S("unsupported");return false}return true}).then(ok=>ok?list(saved):null).then(async rows=>{if(!rows)return;if(savedId)await openSaved(savedId);S("teacher")}).catch(e=>{Msg(e instanceof Error?e.message:"No se pudo cargar el editor.");S("teacher-error")});return}if(q.get("actividad"))void openSaved(q.get("actividad")!).then(()=>S("login")).catch(e=>{Msg(e instanceof Error?e.message:"No se pudo abrir la actividad.");S("login")});else S("teacher-key")},[]);
 useEffect(()=>{if(screen!=="play")return;const timer=setInterval(()=>{Sec(s=>s+1);if(activity.timerMode==="down")Rem(r=>{if(r===null)return null;if(r<=1){TO(true);return 0}return r-1})},1000);return()=>clearInterval(timer)},[screen,activity.timerMode]);

 function patch(id:string,side:Side,values:Partial<PairSide>){Draft(d=>({...d,pairs:d.pairs!.map(pair=>pair.id===id?{...pair,[side]:{...pair[side],...values}}:pair)}))}
 async function teacherEnter(e:React.FormEvent){e.preventDefault();B(true);Msg("");try{if(!await supportsActivityKind(kind)){Msg("Actualiza primero el Apps Script existente con el archivo Code.gs de la plataforma.");S("unsupported");return}await list(keyDraft);K(keyDraft);rememberTeacherKey(keyDraft);const q=new URLSearchParams(location.search);if(q.get("actividad"))await openSaved(q.get("actividad")!);S("teacher")}catch(err){Msg(err instanceof Error?err.message:"No se pudo acceder.")}finally{B(false)}}
 async function save(e:React.FormEvent){e.preventDefault();B(true);Msg("");try{const pairs=(draft.pairs||[]).filter(p=>p.left.text||p.left.imageData||p.left.imageUrl||p.right.text||p.right.imageData||p.right.imageUrl);if(pairs.length<2||pairs.length>30||pairs.some(p=>(!p.left.text&&!p.left.imageData&&!p.left.imageUrl)||(!p.right.text&&!p.right.imageData&&!p.right.imageUrl)))throw Error("Completa entre 2 y 30 tarjetas y los dos lados de cada una.");const body={...draft,id:draft.id||"actividad-"+crypto.randomUUID(),kind,pairs,labels:[]},r=await apiRequest("/api/teacher/activity",{method:"POST",headers:{"x-teacher-key":key},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw Error(data.error||"No se pudo guardar.");await saveActivityAvailability(key,body);A({...data,availableFrom:body.availableFrom||null,availableUntil:body.availableUntil||null});Draft({...data,availableFrom:body.availableFrom||null,availableUntil:body.availableUntil||null});await list(key);Msg("Actividad guardada.")}catch(err){Msg(err instanceof Error?err.message:"No se pudo guardar.")}finally{B(false)}}
 async function submitLogin(e:React.FormEvent){e.preventDefault();B(true);Msg("");try{const r=await apiRequest("/api/student/login",{method:"POST",body:JSON.stringify(login)}),data=await r.json();if(!r.ok)throw Error(data.error||"Usuario o contraseña incorrectos.");saveStudentSession(String(data.token),{...data.student,id:String(data.student.id)});St(data.student);T(data.token);await start(data.student,data.token)}catch(err){Msg(err instanceof Error?err.message:"No se pudo iniciar sesión.")}finally{B(false)}}
 async function start(profile:Student|null=student,tokenValue=token){if(!activity.id||(!previewMode&&(!profile||!tokenValue)))return;if(!(activity.pairs||[]).length){Msg("Esta actividad todavía no tiene tarjetas. El maestro debe terminar de configurarla antes de compartirla.");return}B(true);Msg("");try{if(!previewMode){const q=new URLSearchParams({activityId:activity.id,studentToken:tokenValue,paternalSurname:profile!.paternalSurname,maternalSurname:profile!.maternalSurname,givenNames:profile!.givenNames}),r=await apiRequest("/api/attempts?"+q),data=await r.json();if(!r.ok||!data.canStart)throw Error(data.error||"Ya no tienes intentos.");Att(data.remaining===null?null:Number(data.remaining));}else Att(null);Rem(activity.timerMode==="down"?activity.timeLimitSeconds:null);Sec(0);TO(false);Ans({});F(null);FI(0);Flip(false);const shuffleQuestions=activity.shuffleQuestions??activity.shuffle!==false,shuffleAnswers=activity.shuffleAnswers??activity.shuffle!==false;PlayPairs(shuffleQuestions?shuffle(activity.pairs||[]):[...(activity.pairs||[])]);if(kind==="memory"){const cards=(activity.pairs||[]).flatMap(p=>[{id:p.id+"-a",pairId:p.id,side:"left" as const,content:p.left,open:false,matched:false},{id:p.id+"-b",pairId:p.id,side:"right" as const,content:p.right,open:false,matched:false}]);Deck(shuffleAnswers?shuffle(cards):cards)}S("play")}catch(err){Msg(err instanceof Error?err.message:"No se pudo iniciar.");}finally{B(false)}}
 function sound(frequency:number){if(activity.sound===false||muted)return;try{const ctx=new AudioContext(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=frequency;gain.gain.value=.045;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.12);osc.onended=()=>void ctx.close()}catch{}}
 function chooseCard(index:number){if(first===index||deck[index].matched||deck[index].open)return;const next=deck.map((card,i)=>i===index?{...card,open:true}:card);Deck(next);sound(520);if(first===null){F(index);return}const a=deck[first],b=deck[index];if(a.pairId===b.pairId){next[first]={...next[first],matched:true};next[index]={...next[index],matched:true};Deck(next);Ans(old=>({...old,[a.pairId]:a.pairId}));F(null);sound(760)}else{F(null);window.setTimeout(()=>Deck(current=>current.map((card,i)=>i===first||i===index?{...card,open:false}:card)),850)}}
 async function finish(expired=false){if(!activity.id||(!previewMode&&!student)||busy)return;B(true);Msg("");try{if(previewMode){const correct=Object.keys(answers).length,total=kind==="memory"?activity.pairs?.length||0:activity.pairs?.length||0;Sc({correct,total,grade:total?Math.round(correct/total*100)/10:0,elapsedSeconds:seconds,remainingSeconds:activity.timerMode==="down"?Math.max(0,activity.timeLimitSeconds-seconds):null,timedOut:expired,attemptsRemaining:null});S("result");return}const remainingSeconds=activity.timerMode==="down"?Math.max(0,activity.timeLimitSeconds-seconds):null,r=await apiRequest("/api/submit",{method:"POST",body:JSON.stringify({activityId:activity.id,studentToken:token,paternalSurname:student!.paternalSurname,maternalSurname:student!.maternalSurname,givenNames:student!.givenNames,answers,elapsedSeconds:seconds,remainingSeconds,timedOut:expired||timedOut})}),data=await r.json();if(!r.ok)throw Error(data.error||"No se pudo guardar el resultado.");Sc(data);Att(data.attemptsRemaining===null?null:Number(data.attemptsRemaining));if(activity.showLeaderboard){const board=await apiRequest("/api/leaderboard?activityId="+encodeURIComponent(activity.id));if(board.ok)LB(await board.json() as LeaderboardRow[])}S("result");sound(880)}catch(err){Msg(err instanceof Error?err.message:"No se pudo calificar.");TO(false)}finally{B(false)}}
 useEffect(()=>{if(timedOut&&screen==="play")void finish(true)},[timedOut]);
const pairs=playPairs.length?playPairs:(activity.pairs||[]);

 if(screen==="loading")return <main className="cg-page" aria-live="polite"><section className="cg-login"><span className="cg-kicker">AULA EN JUEGO</span><h1>Abriendo {title.toLocaleLowerCase("es-MX")}</h1><p>Estamos cargando la actividad. Esto puede tardar unos segundos.</p></section></main>;
 if(screen==="teacher-error")return <main className="cg-page"><section className="cg-login"><span className="cg-kicker">NO SE PUDO CARGAR</span><h1>{title}</h1><p>{notice}</p><button className="cg-primary" onClick={()=>location.reload()}>Reintentar</button><a href="?panel=actividades">Volver a Mis actividades</a></section></main>;
 if(screen==="unsupported")return <main className="cg-page"><section className="cg-login"><span className="cg-kicker">PLANTILLA EN PREPARACIÓN</span><h1>{title}</h1><p>{notice}</p><a href="?panel=actividades">Volver a Mis actividades</a></section></main>;
 if(screen==="teacher-key")return <main className="cg-page"><header><a href="?panel=actividades">Mis actividades</a><strong>{title}</strong></header><form className="cg-login" onSubmit={teacherEnter}><span className="cg-kicker">EDITOR DE CONTENIDO</span><h1>Acceso del maestro</h1><label>Clave del maestro<PasswordField required value={keyDraft} onChange={e=>KD(e.target.value)}/></label>{notice&&<p>{notice}</p>}<button className="cg-primary">Continuar</button></form></main>;
 if(screen==="teacher")return <main className="cg-page"><header><a href="?panel=actividades">Mis actividades</a><strong>{title}</strong></header><section className="cg-editor"><EditorWorkflow template={title}/><form onSubmit={save}><EditorContentHeader title={draft.title} instructions={draft.instructions} onTitleChange={value=>Draft(d=>({...d,title:value}))} onInstructionsChange={value=>Draft(d=>({...d,instructions:value}))}/><div className="cg-columns"><b>Lado A</b><b>Lado B</b><span/></div>{draft.pairs!.map((pair,index)=><article className="cg-row" key={pair.id}><span>{index+1}°</span>{(["left","right"] as const).map(side=><div className="cg-cell" key={side}><input aria-label={"Texto tarjeta "+(index+1)} value={pair[side].text} onChange={e=>patch(pair.id,side,{text:e.target.value})} placeholder="Escribe texto"/><EditorImagePicker value={pair[side].imageData||pair[side].imageUrl} onChange={imageData=>patch(pair.id,side,{imageData,imageUrl:""})}/></div>)}<EditorItemActions index={index} onDragReorder={(from,to)=>Draft(d=>({...d,pairs:(()=>{const next=[...d.pairs!],[item]=next.splice(from,1);next.splice(to,0,item);return next})()}))} first={index===0} last={index===draft.pairs!.length-1} deleteDisabled={draft.pairs!.length<=2} onMoveUp={()=>Draft(d=>{const next=[...d.pairs!];[next[index-1],next[index]]=[next[index],next[index-1]];return {...d,pairs:next}})} onMoveDown={()=>Draft(d=>{const next=[...d.pairs!];[next[index],next[index+1]]=[next[index+1],next[index]];return {...d,pairs:next}})} onDuplicate={()=>{const copy={...pair,id:"card-"+crypto.randomUUID(),left:{...pair.left},right:{...pair.right}};Draft(d=>({...d,pairs:[...d.pairs!.slice(0,index+1),copy,...d.pairs!.slice(index+1)]}))}} onDelete={()=>Draft(d=>({...d,pairs:d.pairs!.filter(p=>p.id!==pair.id)}))}/></article>)}<button type="button" className="cg-secondary" onClick={()=>Draft({...draft,pairs:[...draft.pairs!,makePair(draft.pairs!.length+1)]})} disabled={draft.pairs!.length>=30}>＋ Añadir tarjeta</button><ActivitySettings value={draft} onChange={Draft}/>{notice&&<p>{notice}</p>}<button className="cg-primary" disabled={busy}>{busy?"Guardando…":"Guardar actividad"}</button>{activity.id&&<button type="button" className="cg-secondary" onClick={()=>navigator.clipboard.writeText(location.origin+location.pathname+"?juego="+kind+"&actividad="+activity.id).then(()=>Msg("Enlace copiado."))}>Copiar enlace para alumnos</button>}</form></section></main>;
 if(screen==="login")return <main className="cg-page"><form className="cg-login" onSubmit={submitLogin}><span className="cg-kicker">{previewMode?"VISTA PREVIA · SIN REGISTRO":title.toUpperCase()}</span><h1>{activity.title}</h1>{previewMode?<><p>Juega para comprobar la actividad. El resultado no se guardará.</p><button type="button" className="cg-primary" disabled={busy} onClick={()=>void start()}>{busy?"Preparando…":"Probar actividad"}</button><a href="?panel=actividades">Volver a Mis actividades</a></>:student&&token?<><p>Hola, {student.givenNames} {student.paternalSurname}. Tu sesión sigue activa.</p><button type="button" className="cg-primary" disabled={busy} onClick={()=>void start()}>{busy?"Preparando…":"Comenzar actividad"}</button><button type="button" className="cg-secondary" onClick={()=>{clearStudentSession();St(null);T("")}}>Cambiar de alumno</button></>:<><p>Ingresa con tu cuenta de alumno.</p><label>Usuario<input required autoComplete="username" value={login.username} onChange={e=>L({...login,username:e.target.value})}/></label><label>Contraseña<PasswordField autoComplete="current-password" required value={login.password} onChange={e=>L({...login,password:e.target.value})}/></label><button className="cg-primary" disabled={busy}>Entrar y comenzar</button></>}{notice&&<p>{notice}</p>}</form></main>;
 if(screen==="play"&&kind==="flashcards")return <main className="cg-page"><FocusBlurGuard enabled={activity.blurWhenInactive===true} active={screen==="play"}/><header className="cg-playbar"><a href="./">Aula en juego</a><strong>{activity.timerMode==="none"?"":activity.timerMode==="down"?fmt(remaining||0):fmt(seconds)}</strong><span>{flashIndex+1} / {total}</span><small>{attempts===null?"Intentos ilimitados":"Intentos restantes: "+attempts}</small></header><section className="cg-play"><span className="cg-kicker">TARJETA {flashIndex+1} DE {total}</span><h1>{activity.title}</h1><button className={"cg-flash "+(flipped?"flipped":"")} onClick={()=>Flip(!flipped)}><small>{flipped?"REVERSO":"FRENTE"}</small><SideView side={flipped?pairs[flashIndex]?.right:pairs[flashIndex]?.left}/><span>Toca para voltear</span></button><div className="cg-flash-actions"><button className="cg-secondary" onClick={()=>{Ans({...answers,[pairs[flashIndex].id]:pairs[flashIndex].id});if(flashIndex+1<total){FI(flashIndex+1);Flip(false)}}}>Lo recordé</button><button className="cg-secondary" onClick={()=>{const next={...answers};delete next[pairs[flashIndex].id];Ans(next);if(flashIndex+1<total){FI(flashIndex+1);Flip(false)}}}>Necesito repasar</button></div><button className="cg-primary" onClick={()=>void finish()}>{flashIndex===total-1?"Terminar y calificar":"Terminar actividad"}</button></section></main>;
 if(screen==="play")return <main className="cg-page"><FocusBlurGuard enabled={activity.blurWhenInactive===true} active={screen==="play"}/><header className="cg-playbar"><a href="./">Aula en juego</a><strong>{activity.timerMode==="none"?"":activity.timerMode==="down"?fmt(remaining||0):fmt(seconds)}</strong><span>{Object.keys(answers).length} / {total} parejas</span><small>{attempts===null?"Intentos ilimitados":"Intentos restantes: "+attempts}</small></header><section className="cg-play"><span className="cg-kicker">MEMORAMA</span><h1>{activity.title}</h1><div className="cg-memory-grid">{deck.map((card,index)=><button key={card.id} className={"cg-memory-card "+(card.open||card.matched?"visible":"")} disabled={card.matched} onClick={()=>chooseCard(index)}>{card.open||card.matched?<SideView side={card.content}/>:<span>?</span>}</button>)}</div>{notice&&<p>{notice}</p>}<button className="cg-primary" onClick={()=>void finish()}>{busy?"Guardando…":"Terminar y calificar"}</button></section></main>;
 if(screen==="result")return <main className="cg-page"><section className="cg-result"><span className="cg-kicker">{previewMode?"PRUEBA DOCENTE · NO REGISTRADA":"RESULTADO"}</span><h1>{score?.timedOut?"Se acabó el tiempo":"Actividad terminada"}</h1><strong>{score?.correct||0} / {score?.total||total}</strong><p>Calificación: {score?.grade||0} / 10</p><p>Tiempo realizado: {fmt(score?.elapsedSeconds||seconds)}{score?.remainingSeconds!==null&&score?.remainingSeconds!==undefined?" · Sobró "+fmt(score.remainingSeconds):""}</p><p>{previewMode?"Este resultado solo aparece aquí; no se guardó.":score?.attemptsRemaining===null?"Puedes volver a intentarlo.":"Te quedan "+(score?.attemptsRemaining||0)+" intentos."}</p>{previewMode?<button className="cg-primary" onClick={()=>{S("login");Sc(null)}}>Probar de nuevo</button>:score&&(score.attemptsRemaining===null||score.attemptsRemaining>0)&&<button className="cg-primary" onClick={()=>{S("login");Sc(null)}}>Intentar de nuevo</button>}{!previewMode&&activity.showAnswersAtEnd&&<ActivityAnswerKey activity={activity}/ >}{!previewMode&&activity.showLeaderboard&&<ActivityLeaderboard rows={leaderboard}/ >}{previewMode&&<a href="?panel=actividades">Volver a Mis actividades</a>}</section></main>;
 return <main className="cg-page" aria-live="polite"><section className="cg-login"><h1>Abriendo actividad…</h1><p>Espera mientras cargamos el contenido.</p></section></main>;
}
