import { useEffect, useMemo, useState } from "react";
import type { Activity, CrosswordClue } from "./default-activity";
import ActivitySettings from "./ActivitySettings";
import ActivityLeaderboard, { type LeaderboardRow } from "./ActivityLeaderboard";
import ActivityAnswerKey from "./ActivityAnswerKey";
import FocusBlurGuard from "./FocusBlurGuard";
import EditorContentHeader from "./EditorContentHeader";
import EditorImagePicker from "./EditorImagePicker";
import EditorItemActions from "./EditorItemActions";
import EditorWorkflow from "./EditorWorkflow";
import { apiRequest, getTeacherKey, getStudentSession, saveStudentSession, clearStudentSession, supportsActivityKind, saveActivityAvailability } from "./gas-client";
import "./crossword.css";

type Screen="loading"|"teacher-key"|"teacher"|"login"|"play"|"clue"|"result"|"error";
type Placed={id:string;row:number;col:number;vertical:boolean;answer:string};
const uid=()=>crypto.randomUUID();
const fresh=():Activity=>({id:"",kind:"crossword",title:"",instructions:"Toca un número, lee la pista y escribe la respuesta.",timerMode:"none",timeLimitSeconds:180,maxAttempts:3,imageUrl:"",labels:[],shuffle:false,sound:true,scoring:true,crosswordClues:[{id:uid(),clue:"",answer:"",direction:"across"},{id:uid(),clue:"",answer:"",direction:"down"},{id:uid(),clue:"",answer:"",direction:"across"}]});
const clean=(s:string)=>s.toLocaleUpperCase("es-MX").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-ZÑ]/g,"");
const fmt=(n:number)=>`${Math.floor(Math.max(0,n)/60)}:${String(Math.max(0,n)%60).padStart(2,"0")}`;
function layout(clues:CrosswordClue[]){
 const size=31, center=15, grid=Array.from({length:size},()=>Array(size).fill("")),placements:Placed[]=[];
 const canPlace=(answer:string,row:number,col:number,vertical:boolean,allowDisconnected=false)=>{
  if(row<1||col<1||row+(vertical?answer.length:0)>=size-1||col+(vertical?0:answer.length)>=size-1)return false;
  let crossing=false;
  for(let i=0;i<answer.length;i++){const r=row+(vertical?i:0),c=col+(vertical?0:i),cell=grid[r][c];if(cell&&cell!==answer[i])return false;if(cell===answer[i])crossing=true;
   const before=vertical?grid[r-1][c]:grid[r][c-1],after=vertical?grid[r+1][c]:grid[r][c+1];if(before&&i===0&&cell!==answer[i])return false;if(after&&i===answer.length-1&&cell!==answer[i])return false;
   if(!cell){const a=vertical?grid[r][c-1]:grid[r-1][c],b=vertical?grid[r][c+1]:grid[r+1][c];if(a||b)return false;}
  }
  return allowDisconnected||placements.length===0||crossing;
 };
 clues.forEach((item,index)=>{const answer=clean(item.answer);if(!answer)return;const vertical=item.direction==="down";
  if(index===0){const r=vertical?center-Math.floor(answer.length/2):center,c=vertical?center:center-Math.floor(answer.length/2);for(let j=0;j<answer.length;j++)grid[r+(vertical?j:0)][c+(vertical?0:j)]=answer[j];placements.push({id:item.id,row:r,col:c,vertical,answer});return;}
  let found:{row:number;col:number}|null=null;
  for(const p of placements){if(p.vertical===vertical)continue;for(let old=0;old<p.answer.length&&!found;old++)for(let cur=0;cur<answer.length&&!found;cur++)if(p.answer[old]===answer[cur]){const r=p.row+(p.vertical?old:0)-(vertical?cur:0),c=p.col+(p.vertical?0:old)-(vertical?0:cur);if(canPlace(answer,r,c,vertical))found={row:r,col:c};}}
  if(!found){for(let k=0;k<size&&!found;k++){const r=vertical?1:center-10+k*2,c=vertical?center-10+k*2:1;if(canPlace(answer,r,c,vertical,true))found={row:r,col:c};}}
  if(!found)return;for(let j=0;j<answer.length;j++)grid[found.row+(vertical?j:0)][found.col+(vertical?0:j)]=answer[j];placements.push({id:item.id,row:found.row,col:found.col,vertical,answer});
 });
 const occupied=grid.flatMap((row,r)=>row.map((letter,c)=>letter?{r,c}:null).filter(Boolean) as {r:number;c:number}[]);if(!occupied.length)return{grid,placements,minR:0,maxR:0,minC:0,maxC:0};
 return{grid,placements,minR:Math.min(...occupied.map(x=>x.r))-1,maxR:Math.max(...occupied.map(x=>x.r))+1,minC:Math.min(...occupied.map(x=>x.c))-1,maxC:Math.max(...occupied.map(x=>x.c))+1};
}
export default function CrosswordGame(){
 const query=new URLSearchParams(location.search),[screen,setScreen]=useState<Screen>("loading"),[activity,setActivity]=useState<Activity>(fresh),[draft,setDraft]=useState<Activity>(fresh),[teacherKey,setTeacherKey]=useState(getTeacherKey),[keyDraft,setKeyDraft]=useState(""),[student,setStudent]=useState<any>(()=>getStudentSession()?.student||null),[token,setToken]=useState(()=>getStudentSession()?.token||""),[credentials,setCredentials]=useState({username:"",password:""}),[answers,setAnswers]=useState<Record<string,string>>({}),[current,setCurrent]=useState<string>(""),[seconds,setSeconds]=useState(0),[remaining,setRemaining]=useState<number|null>(null),[score,setScore]=useState<any>(null),[leaderboard,setLeaderboard]=useState<LeaderboardRow[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const clues=activity.crosswordClues||[],draftClues=draft.crosswordClues||[],board=useMemo(()=>layout(clues),[clues]);
 useEffect(()=>{const id=query.get("actividad"),teacher=query.get("modo")==="maestro";if(teacher){const key=getTeacherKey();if(!key){setScreen("teacher-key");return}setTeacherKey(key);if(!id&&query.get("nueva")==="1"){const a=fresh();setActivity(a);setDraft(a);setScreen("teacher");void supportsActivityKind("crossword").then(ok=>{if(!ok)setNotice("El editor está listo, pero Apps Script necesita actualizarse para guardar esta plantilla.")}).catch(e=>setNotice(e instanceof Error?e.message:"No se pudo comprobar Apps Script."));return}void supportsActivityKind("crossword").then(ok=>{if(!ok)throw Error("Actualiza el Apps Script con el archivo Code.gs de la plataforma.");if(id)return apiRequest(`/api/activity?id=${encodeURIComponent(id)}`).then(async r=>{if(!r.ok)throw Error("No se encontró la actividad.");const a=await r.json();setActivity(a);setDraft(a)});}).then(()=>setScreen("teacher")).catch(e=>{setNotice(e.message||"No se pudo abrir el editor.");setScreen("error")});return}if(id)void apiRequest(`/api/activity?id=${encodeURIComponent(id)}`).then(async r=>{if(!r.ok)throw Error("No se encontró la actividad.");const a=await r.json();setActivity(a);setDraft(a);setScreen("login")}).catch(e=>{setNotice(e.message);setScreen("error")});else setScreen("error")},[]);
 useEffect(()=>{if(screen!=="play")return;const t=setInterval(()=>{setSeconds(s=>s+1);if(activity.timerMode==="down")setRemaining(r=>{if(r===null)return null;if(r<=1){window.setTimeout(()=>void finish(true),0);return 0}return r-1})},1000);return()=>clearInterval(t)},[screen]);
 function patchClue(id:string,patch:Partial<CrosswordClue>){setDraft(d=>({...d,crosswordClues:(d.crosswordClues||[]).map(x=>x.id===id?{...x,...patch}:x)}))}
 function addClue(){setDraft(d=>({...d,crosswordClues:[...(d.crosswordClues||[]),{id:uid(),clue:"",answer:"",direction:(d.crosswordClues||[]).length%2?"down":"across"}]}))}
 function moveClue(index:number,offset:number){setDraft(d=>{const next=[...(d.crosswordClues||[])],target=index+offset;if(target<0||target>=next.length)return d;[next[index],next[target]]=[next[target],next[index]];return {...d,crosswordClues:next}})}
 function reorderClues(from:number,to:number){setDraft(d=>{const next=[...(d.crosswordClues||[])],[item]=next.splice(from,1);next.splice(to,0,item);return {...d,crosswordClues:next}})}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice("");try{if(!draft.title.trim())throw Error("Escribe el título.");if(draftClues.length<3||draftClues.some(x=>!x.clue.trim()||clean(x.answer).length<2))throw Error("Agrega al menos 3 pistas y completa pregunta y respuesta.");const payload={...draft,id:draft.id||"actividad-"+uid(),kind:"crossword",labels:[],pairs:[]};const r=await apiRequest("/api/teacher/activity",{method:"POST",headers:{"x-teacher-key":teacherKey},body:JSON.stringify(payload)}),data=await r.json();if(!r.ok)throw Error(data.error||"No se pudo guardar.");await saveActivityAvailability(teacherKey,payload);setActivity({...data,availableFrom:payload.availableFrom||null,availableUntil:payload.availableUntil||null});setDraft({...data,availableFrom:payload.availableFrom||null,availableUntil:payload.availableUntil||null});setNotice("Crucigrama guardado. Asígnalo a tus alumnos desde Mis actividades.")}catch(e){setNotice(e instanceof Error?e.message:"No se pudo guardar.")}finally{setBusy(false)}}
 async function teacherLogin(e:React.FormEvent){e.preventDefault();setBusy(true);try{if(!await supportsActivityKind("crossword"))throw Error("Actualiza Apps Script para habilitar Crucigrama.");const r=await apiRequest("/api/teacher/activities",{headers:{"x-teacher-key":keyDraft}}),d=await r.json();if(!r.ok||!Array.isArray(d))throw Error(d.error||"No se validó el acceso docente.");setTeacherKey(keyDraft);localStorage.setItem("platformTeacherKey",keyDraft);localStorage.setItem("aulaTeacherUsername","michelotaner");setDraft(fresh());setScreen("teacher")}catch(e){setNotice(e instanceof Error?e.message:"No se pudo entrar.")}finally{setBusy(false)}}
 async function start(profile=student,sessionToken=token){if(!profile||!sessionToken)return;setBusy(true);try{const q=new URLSearchParams({activityId:activity.id,studentToken:sessionToken,paternalSurname:profile.paternalSurname,maternalSurname:profile.maternalSurname,givenNames:profile.givenNames});const r=await apiRequest("/api/attempts?"+q),d=await r.json();if(!r.ok||!d.canStart)throw Error(d.error||"No puedes iniciar esta actividad.");setRemaining(activity.timerMode==="down"?activity.timeLimitSeconds:null);setSeconds(0);setAnswers({});setScreen("play")}catch(e){setNotice(e instanceof Error?e.message:"No se pudo iniciar.")}finally{setBusy(false)}}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await apiRequest("/api/student/login",{method:"POST",body:JSON.stringify(credentials)}),d=await r.json();if(!r.ok)throw Error(d.error||"Usuario o contraseña incorrectos.");saveStudentSession(d.token,{...d.student,id:d.student.id});setStudent(d.student);setToken(d.token);await start(d.student,d.token)}catch(e){setNotice(e instanceof Error?e.message:"No se pudo iniciar sesión.")}finally{setBusy(false)}}
 async function finish(timeout=false){if(busy)return;setBusy(true);try{const r=await apiRequest("/api/submit",{method:"POST",body:JSON.stringify({activityId:activity.id,studentToken:token,paternalSurname:student?.paternalSurname,maternalSurname:student?.maternalSurname,givenNames:student?.givenNames,answers,elapsedSeconds:seconds,remainingSeconds:activity.timerMode==="down"?Math.max(0,activity.timeLimitSeconds-seconds):null,timedOut:timeout})}),d=await r.json();if(!r.ok)throw Error(d.error||"No se pudo registrar el resultado.");setScore(d);if(activity.showLeaderboard){const board=await apiRequest("/api/leaderboard?activityId="+encodeURIComponent(activity.id));if(board.ok)setLeaderboard(await board.json() as LeaderboardRow[])}setScreen("result")}catch(e){setNotice(e instanceof Error?e.message:"No se pudo calificar.")}finally{setBusy(false)}}
 const reveal=(clueId:string)=>{setCurrent(clueId);setScreen("clue")};
 if(screen==="teacher-key")return <main className="cw-page"><form className="cw-login" onSubmit={teacherLogin}><span>CRUCIGRAMA · DOCENTE</span><h1>Acceso del maestro</h1><label>Clave o sesión docente<input type="password" value={keyDraft} onChange={e=>setKeyDraft(e.target.value)} required/></label>{notice&&<p>{notice}</p>}<button>Continuar</button></form></main>;
 if(screen==="teacher")return <main className="pair-page pair-work-page cw-page"><header className="pair-top"><a href="./">Aula en juego</a><nav><a href="?panel=actividades">Mis actividades</a></nav></header><section className="pair-workspace"><div className="pair-workspace-head"><EditorWorkflow template="Crucigrama"/></div><form className="pair-content-editor cw-content-editor" onSubmit={save}><EditorContentHeader title={draft.title} instructions={draft.instructions} onTitleChange={value=>setDraft(d=>({...d,title:value}))} onInstructionsChange={value=>setDraft(d=>({...d,instructions:value}))}/><h2>Pistas y respuestas</h2><div className="cw-clue-head"><span>#</span><span>Pista</span><span>Respuesta</span><span>Dirección</span><span/></div>{draftClues.map((clue,i)=><div className="cw-clue-row" key={clue.id}><b>{i+1}°</b><div className="cw-clue-input-image"><input aria-label={`Pista ${i+1}`} value={clue.clue} onChange={e=>patchClue(clue.id,{clue:e.target.value})} placeholder="Escribe la pregunta"/><EditorImagePicker value={clue.imageData||clue.imageUrl} onChange={imageData=>patchClue(clue.id,{imageData,imageUrl:""})}/></div><input aria-label={`Respuesta ${i+1}`} value={clue.answer} onChange={e=>patchClue(clue.id,{answer:e.target.value})} placeholder="Respuesta"/><select value={clue.direction||"across"} onChange={e=>patchClue(clue.id,{direction:e.target.value as "across"|"down"})}><option value="across">Horizontal</option><option value="down">Vertical</option></select><EditorItemActions index={i} onDragReorder={reorderClues} first={i===0} last={i===draftClues.length-1} deleteDisabled={draftClues.length<=3} onMoveUp={()=>moveClue(i,-1)} onMoveDown={()=>moveClue(i,1)} onDuplicate={()=>setDraft(d=>({...d,crosswordClues:[...draftClues.slice(0,i+1),{...clue,id:uid()},...draftClues.slice(i+1)]}))} onDelete={()=>setDraft(d=>({...d,crosswordClues:(d.crosswordClues||[]).filter(x=>x.id!==clue.id)}))}/></div>)}<button type="button" className="pair-add-item" onClick={addClue}>＋ Añadir pista</button><small className="pair-count">Mín. 3 pistas</small><ActivitySettings value={draft} onChange={setDraft}/>{notice&&<p role="status" className="pair-error">{notice}</p>}<div className="pair-ready-row"><span>{draftClues.length} pistas · {draftClues.filter(clue=>clue.clue.trim()&&clue.answer.trim()).length} completas</span><button className="pair-primary" disabled={busy}>{busy?"Guardando…":"Guardar actividad"}</button></div>{activity.id&&<button type="button" className="pair-secondary cw-copy-link" onClick={()=>navigator.clipboard.writeText(location.origin+location.pathname+`?juego=crossword&actividad=${activity.id}`).then(()=>setNotice("Enlace copiado."))}>Copiar enlace</button>}</form></section></main>;
 if(screen==="login")return <main className="cw-page"><form className="cw-login" onSubmit={login}><span>CRUCIGRAMA</span><h1>{activity.title}</h1>{student&&token?<><p>Sesión activa: {student.givenNames} {student.paternalSurname}</p><button type="button" onClick={()=>void start()} disabled={busy}>Comenzar</button><button type="button" className="cw-secondary" onClick={()=>{clearStudentSession();setStudent(null);setToken("")}}>Cambiar de alumno</button></>:<><p>Inicia sesión con tu cuenta para resolver las pistas.</p><label>Usuario<input autoComplete="username" value={credentials.username} onChange={e=>setCredentials({...credentials,username:e.target.value})} required/></label><label>Contraseña<input type="password" autoComplete="current-password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})} required/></label><button disabled={busy}>Entrar</button></>}{notice&&<p>{notice}</p>}</form></main>;
 if(screen==="play"||screen==="clue")return <main className="cw-page"><FocusBlurGuard enabled={activity.blurWhenInactive===true} active={screen==="play"}/><header className="cw-head"><a href="?panel=alumno">← Mis actividades</a><b>{activity.timerMode==="none"?"":activity.timerMode==="down"?fmt(remaining||0):fmt(seconds)}</b><span>{Object.keys(answers).length}/{clues.length} pistas</span></header><section className="cw-play"><span className="cw-kicker">CRUCIGRAMA</span><h1>{activity.title}</h1><p>{activity.instructions}</p><div className="cw-board-wrap"><div className="cw-board" style={{gridTemplateColumns:`repeat(${board.maxC-board.minC+1}, 30px)`}}>{Array.from({length:board.maxR-board.minR+1},(_,ri)=>Array.from({length:board.maxC-board.minC+1},(_,ci)=>{const r=ri+board.minR,c=ci+board.minC,letter=board.grid[r]?.[c],p=board.placements.find(x=>x.row===r&&x.col===c);return <button key={`${r}:${c}`} className={`cw-cell ${letter?"filled":"black"} ${p?"numbered":""} ${p&&current===p.id?"active":""}`} disabled={!p} onClick={()=>p&&reveal(p.id)} aria-label={p?`Pista ${board.placements.indexOf(p)+1}`:undefined}>{p&&<small>{board.placements.indexOf(p)+1}</small>}{letter&&answers[p?.id||""]?letter:""}</button>}))}</div></div><div className="cw-clue-list"><h2>Elige una pista</h2>{clues.map((c,i)=><button key={c.id} onClick={()=>reveal(c.id)} className={answers[c.id]?"done":""}><b>{i+1}. {c.direction==="down"?"↓":"→"}</b><span>{c.clue}</span><small>{answers[c.id]?"Respondida":"Pendiente"}</small></button>)}</div>{notice&&<p role="status">{notice}</p>}<button className="cw-primary" onClick={()=>void finish()} disabled={busy}>Terminar y calificar</button></section>{screen==="clue"&&<div className="cw-modal"><form onSubmit={e=>{e.preventDefault();setScreen("play")}}><button type="button" className="cw-modal-back" onClick={()=>setScreen("play")}>← Volver al tablero</button><span className="cw-kicker">PISTA {board.placements.findIndex(p=>p.id===current)+1}</span><h2>{clues.find(c=>c.id===current)?.clue}</h2>{(clues.find(c=>c.id===current)?.imageData||clues.find(c=>c.id===current)?.imageUrl)&&<img className="cw-clue-image" src={clues.find(c=>c.id===current)?.imageData||clues.find(c=>c.id===current)?.imageUrl||""} alt="Apoyo visual de la pista"/>}<label>Tu respuesta<input autoFocus value={answers[current]||""} onChange={e=>setAnswers({...answers,[current]:e.target.value})}/></label><div className="cw-modal-actions"><button type="button" className="cw-secondary" onClick={()=>setScreen("play")}>Dejar pendiente</button><button className="cw-primary">Guardar y volver</button></div></form></div>}</main>;
 if(screen==="result")return <main className="cw-page"><section className="cw-result"><span className="cw-kicker">RESULTADO</span><h1>{score?.timedOut?"Se acabó el tiempo":"Crucigrama terminado"}</h1><strong>{score?.correct}/{score?.total}</strong><p>Calificación: {score?.grade}/10 · Tiempo: {fmt(score?.elapsedSeconds||seconds)}</p><p>{score?.attemptsRemaining===null?"Intentos ilimitados":`Te quedan ${score?.attemptsRemaining||0} intentos`}</p>{activity.showAnswersAtEnd&&<ActivityAnswerKey activity={activity}/ >}{activity.showLeaderboard&&<ActivityLeaderboard rows={leaderboard}/>}<a href="?panel=alumno">Volver al panel</a></section></main>;
 return <main className="cw-page"><section className="cw-login"><h1>{notice||"Abriendo crucigrama…"}</h1></section></main>;
}
