import { useEffect, useMemo, useRef, useState } from "react";
import type { Activity, WheelEntry } from "./default-activity";
import ActivitySettings from "./ActivitySettings";
import ActivityLeaderboard, { type LeaderboardRow } from "./ActivityLeaderboard";
import ActivityAnswerKey from "./ActivityAnswerKey";
import FocusBlurGuard from "./FocusBlurGuard";
import EditorContentHeader from "./EditorContentHeader";
import EditorImagePicker from "./EditorImagePicker";
import EditorItemActions from "./EditorItemActions";
import EditorWorkflow from "./EditorWorkflow";
import { apiRequest, forgetTeacherKey, getTeacherKey, rememberTeacherKey, supportsActivityKind, saveActivityAvailability, getStudentSession, saveStudentSession, clearStudentSession } from "./gas-client";
import "./extra-game.css";

type Kind = "roulette" | "word-search" | "complete-phrase";
type Student = { paternalSurname: string; maternalSurname: string; givenNames: string };
type Result = { correct:number; total:number; grade:number; elapsedSeconds:number; remainingSeconds:number|null; timedOut:boolean; attemptsRemaining:number|null };
type Cell = { letter:string; row:number; col:number };
const uid=()=>crypto.randomUUID();
const blank=(kind:Kind):Activity=>({id:"",kind,title:"",instructions:kind==="roulette"?"Gira la rueda y completa el reto que salga.":kind==="complete-phrase"?"Completa cada frase seleccionando sus letras en la cuadrícula.":"Encuentra todas las palabras en la cuadrícula.",timerMode:"none",timeLimitSeconds:180,maxAttempts:3,imageUrl:"",labels:[],shuffle:true,sound:true,scoring:true,wheelEntries:kind==="roulette"?[{id:uid(),text:""},{id:uid(),text:""}]:[],wordSearchWords:kind==="word-search"?["","",""]:[],wordSearchGridSize:10,wordSearchShowClues:false,wordSearchClues:{},phraseGridSize:10,wordSearchDirections:["horizontal","vertical","diagonal"],sentences:kind==="complete-phrase"?[{id:uid(),before:"",answer:"",after:""}]:[]});
const fmt=(n:number)=>{const v=Math.max(0,Math.floor(n));return Math.floor(v/60)+":"+String(v%60).padStart(2,"0")};
const normalize=(value:string)=>value.toLocaleUpperCase("es-MX").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-ZÑ]/g,"");
const shuffle=<T,>(items:T[])=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
function playTone(kind:Kind,enabled:boolean){if(!enabled)return;try{const context=new AudioContext(),osc=context.createOscillator(),gain=context.createGain();osc.frequency.value=kind==="roulette"?480:660;gain.gain.value=.035;osc.connect(gain);gain.connect(context.destination);osc.start();osc.stop(context.currentTime+.12);osc.onended=()=>void context.close()}catch{}}
function buildGrid(words:string[],size:number):{grid:Cell[][];placements:Array<{word:string;cells:Array<{row:number;col:number}>}>}{
 const dirs=[[0,1],[1,0],[1,1],[1,-1],[-1,1],[-1,0],[0,-1],[-1,-1]];
 const normalized=words.map(word=>({word,letters:normalize(word)})).filter(x=>x.letters);
 for(let attempt=0;attempt<100;attempt++){
  const cells=Array.from({length:size},()=>Array.from({length:size},()=> ""));
  const placements:Array<{word:string;cells:Array<{row:number;col:number}>}>=[];
  let failed=false;
  for(const item of [...normalized].sort((a,b)=>b.letters.length-a.letters.length)){
   let placed=false;
   for(let tries=0;tries<300&&!placed;tries++){
    const [dr,dc]=dirs[Math.floor(Math.random()*dirs.length)],r=Math.floor(Math.random()*size),c=Math.floor(Math.random()*size);
    const endR=r+dr*(item.letters.length-1),endC=c+dc*(item.letters.length-1);
    if(endR<0||endR>=size||endC<0||endC>=size)continue;
    const coords=Array.from({length:item.letters.length},(_,i)=>({row:r+dr*i,col:c+dc*i}));
    if(coords.some((p,i)=>cells[p.row][p.col]&&cells[p.row][p.col]!==item.letters[i]))continue;
    coords.forEach((p,i)=>cells[p.row][p.col]=item.letters[i]);
    placements.push({word:item.word,cells:coords});placed=true;
   }
   if(!placed){failed=true;break}
  }
  if(!failed){
   const letters="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
   return {grid:cells.map((row,r)=>row.map((letter,col)=>({letter:letter||letters[Math.floor(Math.random()*letters.length)],row:r,col}))),placements};
  }
 }
 throw new Error("No se pudo crear la cuadrícula. Reduce las palabras o aumenta su tamaño.");
}
export default function ExtraGame({kind}:{kind:Kind}){
 const typeTitle=kind==="roulette"?"Rueda giratoria":kind==="complete-phrase"?"Completar la frase":"Sopa de letras";
 const [screen,S]=useState("loading"),[activity,A]=useState<Activity>(()=>blank(kind)),[draft,D]=useState<Activity>(()=>blank(kind)),[saved,Sa]=useState<Activity[]>([]);
 const [key,K]=useState(getTeacherKey()),[keyDraft,KD]=useState("");
 const [student,St]=useState<Student|null>(()=>{const saved=getStudentSession()?.student;return saved?{paternalSurname:saved.paternalSurname,maternalSurname:saved.maternalSurname,givenNames:saved.givenNames}:null}),[token,T]=useState(()=>getStudentSession()?.token||""),[login,L]=useState({username:"",password:""});
 const [busy,B]=useState(false),[notice,N]=useState(""),[elapsed,E]=useState(0),[remaining,R]=useState<number|null>(null),[timedOut,TO]=useState(false),[attempts,At]=useState<number|null>(null),[result,Res]=useState<Result|null>(null),[leaderboard,LB]=useState<LeaderboardRow[]>([]);
 const [current,C]=useState<WheelEntry|null>(null),[completed,Done]=useState<string[]>([]),[grid,G]=useState<Cell[][]>([]),[found,F]=useState<string[]>([]),[selected,Sel]=useState<{row:number;col:number}|null>(null);
 const [rotation,Rot]=useState(0),[gridVersion,GV]=useState(0);
 const [dragPath,DragPath]=useState<Array<{row:number;col:number}>>([]);
 const dragOrigin=useRef<Cell|null>(null),priorSelected=useRef<{row:number;col:number}|null>(null),dragging=useRef(false),skipClick=useRef(false);
 const entries=draft.wheelEntries||[];
 const wordList=kind==="complete-phrase"?(activity.sentences||[]).map(sentence=>sentence.answer):activity.wordSearchWords||[];
 const gridSize=Math.min(15,Math.max(10,Number(kind==="complete-phrase"?activity.phraseGridSize:activity.wordSearchGridSize)||10));
 const total=kind==="roulette"?(activity.wheelEntries||[]).length:kind==="complete-phrase"?(activity.sentences||[]).length:wordList.length;
 const title=activity.title||typeTitle;
 const progress=useMemo(()=>kind==="roulette"?completed.length:found.length,[kind,completed,found]);

 async function list(accessKey:string){const response=await apiRequest("/api/teacher/activities",{headers:{"x-teacher-key":accessKey}}),data=await response.json();if(!response.ok||!Array.isArray(data))throw Error(data.error||"No se pudieron cargar las actividades.");const filtered=(data as Activity[]).filter(item=>item.kind===kind);Sa(filtered);return filtered}
 async function open(id:string){const response=await apiRequest("/api/activity?id="+encodeURIComponent(id)),data=await response.json();if(!response.ok)throw Error(data.error||"No se encontró la actividad.");A(data);D(data);return data as Activity}
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get("modo")==="maestro"){const accessKey=getTeacherKey();if(!accessKey){S("teacher-key");return}K(accessKey);const savedId=q.get("actividad");if(!savedId&&q.get("nueva")==="1"){A(blank(kind));D(blank(kind));S("teacher");void supportsActivityKind(kind).then(ok=>{if(!ok){N("El editor está listo, pero Apps Script necesita actualizarse para guardar esta plantilla.");return}return list(accessKey)}).catch(error=>N(error instanceof Error?error.message:"No se pudo actualizar la lista de actividades."));return}void supportsActivityKind(kind).then(ok=>{if(!ok){N("Actualiza el Apps Script existente con el archivo Code.gs de la plataforma.");S("unsupported");return false}return true}).then(ok=>ok?list(accessKey):null).then(async rows=>{if(!rows)return;if(savedId)await open(savedId);S("teacher")}).catch(error=>{N(error instanceof Error?error.message:"No se pudo abrir el editor.");S("teacher-error")});return}const id=q.get("actividad");if(id)void open(id).then(()=>S("login")).catch(error=>{N(error instanceof Error?error.message:"No se pudo abrir la actividad.");S("login")});else S("teacher-key")},[]);
 useEffect(()=>{if(screen!=="play")return;const timer=window.setInterval(()=>{E(value=>value+1);if(activity.timerMode==="down")R(value=>{if(value===null)return null;if(value<=1){TO(true);return 0}return value-1})},1000);return()=>window.clearInterval(timer)},[screen,activity.timerMode]);
 useEffect(()=>{if(timedOut&&screen==="play")void finish(true)},[timedOut,screen]);
 async function enterTeacher(event:React.FormEvent){event.preventDefault();B(true);N("");try{if(!await supportsActivityKind(kind))throw Error("Actualiza primero el Apps Script existente con el archivo Code.gs de la plataforma.");await list(keyDraft);K(keyDraft);rememberTeacherKey(keyDraft);const q=new URLSearchParams(location.search);if(q.get("actividad"))await open(q.get("actividad")!);S("teacher")}catch(error){N(error instanceof Error?error.message:"No se pudo validar la clave.");}finally{B(false)}}
 function updateEntry(id:string,patch:Partial<WheelEntry>){D(value=>({...value,wheelEntries:(value.wheelEntries||[]).map(entry=>entry.id===id?{...entry,...patch}:entry)}))}
 function moveList<T>(list:T[],index:number,offset:number){const next=[...list],to=index+offset;if(to<0||to>=next.length)return next;[next[index],next[to]]=[next[to],next[index]];return next}
 function moveListTo<T>(list:T[],from:number,to:number){const next=[...list],[item]=next.splice(from,1);next.splice(to,0,item);return next}
 async function save(event:React.FormEvent){event.preventDefault();B(true);N("");try{if(kind==="roulette"&&(entries.length<2||entries.some(e=>!e.text.trim()&&!e.imageUrl&&!e.imageData)))throw Error("Agrega al menos dos opciones con texto o imagen.");if(kind==="word-search"){const words=(draft.wordSearchWords||[]).map(x=>x.trim()).filter(Boolean),size=Number(draft.wordSearchGridSize)||10;if(words.length<3)throw Error("Agrega al menos tres palabras.");if(words.some(word=>normalize(word).length>size))throw Error("Una palabra no cabe en la cuadrícula. Aumenta el tamaño o acórtala.");if(new Set(words.map(normalize)).size!==words.length)throw Error("No repitas palabras.");D(value=>({...value,wordSearchWords:words}))}if(kind==="complete-phrase"){const sentences=draft.sentences||[],size=Number(draft.phraseGridSize)||10;if(sentences.length<1||sentences.some(sentence=>!sentence.before.trim()||!sentence.answer.trim()))throw Error("Cada frase necesita una pista y una respuesta.");if(sentences.some(sentence=>normalize(sentence.answer).length>size))throw Error("La respuesta más larga no cabe en la cuadrícula elegida.");if(new Set(sentences.map(sentence=>normalize(sentence.answer))).size!==sentences.length)throw Error("Cada respuesta debe ser diferente para reconocerla en la cuadrícula.")}
  const payload={...draft,id:draft.id||"actividad-"+uid(),kind,labels:[],pairs:[]};
  const response=await apiRequest("/api/teacher/activity",{method:"POST",headers:{"x-teacher-key":key},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Error(data.error||"No se pudo guardar la actividad.");await saveActivityAvailability(key,payload);A({...data,availableFrom:payload.availableFrom||null,availableUntil:payload.availableUntil||null});D({...data,availableFrom:payload.availableFrom||null,availableUntil:payload.availableUntil||null});await list(key);N("Actividad guardada.")}catch(error){N(error instanceof Error?error.message:"No se pudo guardar.")}finally{B(false)}}
 async function loginStudent(event:React.FormEvent){event.preventDefault();B(true);N("");try{const response=await apiRequest("/api/student/login",{method:"POST",body:JSON.stringify(login)}),data=await response.json();if(!response.ok)throw Error(data.error||"Usuario o contraseña incorrectos.");saveStudentSession(String(data.token),{...data.student,id:String(data.student.id)});St(data.student);T(data.token);await start(data.student,data.token)}catch(error){N(error instanceof Error?error.message:"No se pudo iniciar sesión.")}finally{B(false)}}
 async function start(profile:Student|null=student,tokenValue=token){if(!activity.id||!profile||!tokenValue)return;if(total===0){N("Esta actividad todavía no tiene contenido. El maestro debe terminar de configurarla antes de compartirla.");return}B(true);N("");try{const q=new URLSearchParams({activityId:activity.id,studentToken:tokenValue,paternalSurname:profile.paternalSurname,maternalSurname:profile.maternalSurname,givenNames:profile.givenNames}),response=await apiRequest("/api/attempts?"+q),data=await response.json();if(!response.ok||!data.canStart)throw Error(data.error||"Ya utilizaste todos tus intentos.");At(data.remaining===null?null:Number(data.remaining));E(0);R(activity.timerMode==="down"?activity.timeLimitSeconds:null);TO(false);Res(null);Done([]);F([]);C(null);Sel(null);
  if(kind==="word-search"||kind==="complete-phrase"){try{const targets=kind==="complete-phrase"?(activity.sentences||[]).map(sentence=>sentence.answer):activity.wordSearchWords||[];const made=buildGrid(targets,gridSize);G(made.grid);GV(value=>value+1)}catch(error){throw Error(error instanceof Error?error.message:"No se pudo preparar la cuadrícula.")}}
  S("play")}catch(error){N(error instanceof Error?error.message:"No se pudo comenzar.")}finally{B(false)}}
 async function finish(expired=false){if(!activity.id||!student||busy)return;B(true);N("");try{const answers=kind==="roulette"?{completedIds:completed}:kind==="complete-phrase"?Object.fromEntries((activity.sentences||[]).map(sentence=>[sentence.id,found.includes(sentence.answer)?sentence.answer:""])):{foundWords:found};const response=await apiRequest("/api/submit",{method:"POST",body:JSON.stringify({activityId:activity.id,studentToken:token,paternalSurname:student.paternalSurname,maternalSurname:student.maternalSurname,givenNames:student.givenNames,answers,elapsedSeconds:elapsed,remainingSeconds:activity.timerMode==="down"?Math.max(0,activity.timeLimitSeconds-elapsed):null,timedOut:expired||timedOut})}),data=await response.json();if(!response.ok)throw Error(data.error||"No se pudo registrar el resultado.");Res(data);At(data.attemptsRemaining===null?null:Number(data.attemptsRemaining));if(activity.showLeaderboard){const board=await apiRequest("/api/leaderboard?activityId="+encodeURIComponent(activity.id));if(board.ok)LB(await board.json() as LeaderboardRow[])}S("result")}catch(error){N(error instanceof Error?error.message:"No se pudo calificar.");TO(false)}finally{B(false)}}
 function spin(){const pool=(activity.wheelEntries||[]).filter(entry=>!completed.includes(entry.id));if(!pool.length){N("Ya recorriste todos los retos.");return}const choice=pool[Math.floor(Math.random()*pool.length)];C(choice);Rot(value=>value+1080+Math.floor(Math.random()*360));playTone(kind,activity.sound!==false)}
 function checkPath(start:{row:number;col:number},end:{row:number;col:number}){const dr=end.row-start.row,dc=end.col-start.col,len=Math.max(Math.abs(dr),Math.abs(dc))+1;if(!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc))){N("Selecciona letras en línea recta.");Sel(null);return}
  const stepR=Math.sign(dr),stepC=Math.sign(dc),letters:string[]=[];for(let i=0;i<len;i++)letters.push(grid[start.row+stepR*i]?.[start.col+stepC*i]?.letter||"");
  const candidate=letters.join(""),reverse=[...letters].reverse().join("");const match=wordList.find(word=>!found.includes(word)&&[candidate,reverse].includes(normalize(word)));
  if(match){F(value=>[...value,match]);playTone(kind,activity.sound!==false);N("¡Encontraste "+match+"!")}else N("Esa línea no forma una palabra de la lista.");
  Sel(null);DragPath([])}
 function chooseCell(cell:Cell){if(!selected){Sel({row:cell.row,col:cell.col});return}checkPath(selected,cell)}
 function pointerMoveGrid(event:React.PointerEvent<HTMLDivElement>){if(!dragging.current)return;const element=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>("[data-letter-cell]");if(!element)return;const row=Number(element.dataset.row),col=Number(element.dataset.col),origin=dragOrigin.current;if(!origin)return;const dr=row-origin.row,dc=col-origin.col;if(!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc)))return;const length=Math.max(Math.abs(dr),Math.abs(dc))+1,stepR=Math.sign(dr),stepC=Math.sign(dc);DragPath(Array.from({length},(_,index)=>({row:origin.row+stepR*index,col:origin.col+stepC*index})))}
 function pointerStart(event:React.PointerEvent<HTMLButtonElement>,cell:Cell){dragOrigin.current=cell;priorSelected.current=selected;dragging.current=true;skipClick.current=true;Sel({row:cell.row,col:cell.col});DragPath([{row:cell.row,col:cell.col}]);event.preventDefault()}
 function pointerEnd(event:React.PointerEvent<HTMLDivElement>){if(!dragging.current)return;dragging.current=false;const origin=dragOrigin.current;const element=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>("[data-letter-cell]");if(origin&&element){const end={row:Number(element.dataset.row),col:Number(element.dataset.col)};if(end.row!==origin.row||end.col!==origin.col)checkPath(origin,end);else if(priorSelected.current)checkPath(priorSelected.current,end);else{Sel(origin);DragPath([])}}else Sel(null);window.setTimeout(()=>{skipClick.current=false},0)}
 async function copyShare(){const link=location.origin+location.pathname+"?juego="+kind+"&actividad="+activity.id;try{await navigator.clipboard.writeText(link);N("Enlace copiado.")}catch{window.prompt("Copia el enlace para tus alumnos:",link)}}
 if(screen==="loading")return <main className="extra-page" aria-live="polite"><section className="extra-login"><span className="extra-kicker">AULA EN JUEGO</span><h1>Abriendo {typeTitle.toLocaleLowerCase("es-MX")}</h1><p>Estamos cargando la actividad. Esto puede tardar unos segundos.</p></section></main>;
 if(screen==="teacher-error")return <main className="extra-page"><section className="extra-login"><span className="extra-kicker">NO SE PUDO CARGAR</span><h1>{typeTitle}</h1><p>{notice}</p><button className="extra-primary" onClick={()=>location.reload()}>Reintentar</button><a href="?panel=actividades">Volver a Mis actividades</a></section></main>;
 if(screen==="unsupported")return <main className="extra-page"><section className="extra-login"><span className="extra-kicker">PLANTILLA EN PREPARACIÓN</span><h1>{typeTitle}</h1><p>{notice}</p><a href="?panel=actividades">Volver a Mis actividades</a></section></main>;
 if(screen==="teacher-key")return <main className="extra-page"><header><a href="?panel=actividades">Mis actividades</a><b>{typeTitle}</b></header><form className="extra-login" onSubmit={enterTeacher}><span className="extra-kicker">EDITOR DE ACTIVIDAD</span><h1>Acceso del maestro</h1><label>Clave del maestro<input type="password" value={keyDraft} onChange={e=>KD(e.target.value)} required/></label>{notice&&<p role="status">{notice}</p>}<button className="extra-primary">Continuar</button></form></main>;
 if(screen==="teacher")return <main className="extra-page"><header><a href="?panel=actividades">Mis actividades</a><b>{typeTitle}</b></header><section className="extra-editor"><div className="extra-editor-head"><EditorWorkflow template={typeTitle}/>{activity.id&&<button type="button" className="extra-secondary" onClick={()=>void copyShare()}>Compartir ↗</button>}</div><form onSubmit={save}><EditorContentHeader title={draft.title} instructions={draft.instructions} onTitleChange={value=>D(d=>({...d,title:value}))} onInstructionsChange={value=>D(d=>({...d,instructions:value}))}/>
 {kind==="roulette"&&<section><div className="extra-section-head"><div><h2>Opciones de la ruleta</h2><p>Cada giro elige un reto diferente hasta recorrerlos todos.</p></div><button type="button" className="extra-secondary" onClick={()=>D({...draft,wheelEntries:[...entries,{id:uid(),text:""}]})}>＋ Agregar opción</button></div>{entries.map((entry,index)=><article className="extra-row extra-compact-row" key={entry.id}><header><b>{index+1}°</b><EditorItemActions first={index===0} last={index===entries.length-1} index={index} onDragReorder={(from,to)=>D(d=>({...d,wheelEntries:moveListTo(d.wheelEntries||[],from,to)}))} deleteDisabled={entries.length<=2} onMoveUp={()=>D(d=>({...d,wheelEntries:moveList(d.wheelEntries||[],index,-1)}))} onMoveDown={()=>D(d=>({...d,wheelEntries:moveList(d.wheelEntries||[],index,1)}))} onDuplicate={()=>{const copy={...entry,id:uid()};D(d=>({...d,wheelEntries:[...d.wheelEntries!.slice(0,index+1),copy,...d.wheelEntries!.slice(index+1)]}))}} onDelete={()=>D(d=>({...d,wheelEntries:d.wheelEntries!.filter(item=>item.id!==entry.id)}))}/></header><label>Texto o reto<input value={entry.text} onChange={e=>updateEntry(entry.id,{text:e.target.value})} placeholder="Escribe una pregunta, tema o reto"/></label><div className="extra-upload"><span>Imagen</span><EditorImagePicker value={entry.imageData||entry.imageUrl} onChange={imageData=>updateEntry(entry.id,{imageData,imageUrl:""})}/></div></article>)}</section>}
 {kind==="word-search"&&<section><h2>Palabras para buscar</h2><p>Se aceptan espacios y acentos; la cuadrícula muestra las letras juntas.</p><label>Ayuda para el alumno<select value={draft.wordSearchShowClues?"clues":"words"} onChange={e=>D({...draft,wordSearchShowClues:e.target.value==="clues"})}><option value="words">Mostrar palabras</option><option value="clues">Mostrar pistas</option></select></label>{(draft.wordSearchWords||[]).map((word,index)=><article className="extra-word-edit-row" key={index}><label className="extra-word-field">Palabra {index+1}<input maxLength={30} value={word} onChange={e=>D(d=>({...d,wordSearchWords:(d.wordSearchWords||[]).map((x,i)=>i===index?e.target.value:x)}))} placeholder="Ej. sistema solar"/>{draft.wordSearchShowClues&&<input value={draft.wordSearchClues?.[word]||""} onChange={e=>D(d=>({...d,wordSearchClues:{...(d.wordSearchClues||{}),[word]:e.target.value}}))} placeholder="Escribe una pista para esta palabra"/>}</label><EditorItemActions first={index===0} last={index===(draft.wordSearchWords||[]).length-1} index={index} onDragReorder={(from,to)=>D(d=>({...d,wordSearchWords:moveListTo(d.wordSearchWords||[],from,to)}))} deleteDisabled={(draft.wordSearchWords||[]).length<=3} onMoveUp={()=>D(d=>({...d,wordSearchWords:moveList(d.wordSearchWords||[],index,-1)}))} onMoveDown={()=>D(d=>({...d,wordSearchWords:moveList(d.wordSearchWords||[],index,1)}))} onDuplicate={()=>D(d=>({...d,wordSearchWords:[...(d.wordSearchWords||[]).slice(0,index+1),word,...(d.wordSearchWords||[]).slice(index+1)]}))} onDelete={()=>D(d=>({...d,wordSearchWords:(d.wordSearchWords||[]).filter((_,i)=>i!==index)}))}/></article>)}<button type="button" className="extra-secondary" disabled={(draft.wordSearchWords||[]).length>=20} onClick={()=>D({...draft,wordSearchWords:[...(draft.wordSearchWords||[]),""]})}>＋ Agregar palabra</button><label>Tamaño de cuadrícula<select value={draft.wordSearchGridSize||10} onChange={e=>D({...draft,wordSearchGridSize:Number(e.target.value)})}>{[10,11,12,13,14,15].map(size=><option key={size} value={size}>{size} × {size}</option>)}</select></label></section>}
 {kind==="complete-phrase"&&<section><h2>Frases y respuestas</h2><p>La respuesta se esconderá en la cuadrícula de letras. El alumno la seleccionará arrastrando.</p>{(draft.sentences||[]).map((sentence,index)=><article className="extra-row extra-compact-row phrase-edit-row" key={sentence.id}><header><b>{index+1}°</b><EditorItemActions first={index===0} last={index===(draft.sentences||[]).length-1} index={index} onDragReorder={(from,to)=>D(d=>({...d,sentences:moveListTo(d.sentences||[],from,to)}))} deleteDisabled={(draft.sentences||[]).length<=1} onMoveUp={()=>D(d=>({...d,sentences:moveList(d.sentences||[],index,-1)}))} onMoveDown={()=>D(d=>({...d,sentences:moveList(d.sentences||[],index,1)}))} onDuplicate={()=>{const copy={...sentence,id:uid()};D(d=>({...d,sentences:[...d.sentences!.slice(0,index+1),copy,...d.sentences!.slice(index+1)]}))}} onDelete={()=>D(d=>({...d,sentences:d.sentences!.filter(item=>item.id!==sentence.id)}))}/></header><label>Frase antes del espacio<input value={sentence.before} onChange={e=>D(d=>({...d,sentences:d.sentences!.map(item=>item.id===sentence.id?{...item,before:e.target.value}:item)}))} placeholder="Ej. El planeta rojo es"/></label><label>Respuesta<input value={sentence.answer} onChange={e=>D(d=>({...d,sentences:d.sentences!.map(item=>item.id===sentence.id?{...item,answer:e.target.value}:item)}))} placeholder="Marte"/></label><label>Texto después (opcional)<input value={sentence.after} onChange={e=>D(d=>({...d,sentences:d.sentences!.map(item=>item.id===sentence.id?{...item,after:e.target.value}:item)}))}/></label><div className="extra-upload"><span>Imagen</span><EditorImagePicker value={sentence.imageData||sentence.imageUrl} onChange={imageData=>D(d=>({...d,sentences:d.sentences!.map(item=>item.id===sentence.id?{...item,imageData,imageUrl:""}:item)}))}/></div></article>)}<button type="button" className="extra-secondary" onClick={()=>D({...draft,sentences:[...(draft.sentences||[]),{id:uid(),before:"",answer:"",after:""}]})}>＋ Añadir frase</button><label className="phrase-grid-size">Tamaño de cuadrícula<select value={draft.phraseGridSize||10} onChange={e=>D({...draft,phraseGridSize:Number(e.target.value)})}>{[10,11,12,13,14,15].map(size=><option key={size} value={size}>{size} × {size}</option>)}</select></label></section>}
 <ActivitySettings value={draft} onChange={D}/>{notice&&<p role="status">{notice}</p>}<button className="extra-primary" disabled={busy}>{busy?"Guardando…":"Guardar actividad"}</button></form></section></main>;
 if(screen==="login")return <main className="extra-page"><form className="extra-login" onSubmit={loginStudent}><span className="extra-kicker">{typeTitle.toUpperCase()}</span><h1>{activity.title}</h1>{student&&token?<><p>Hola, {student.givenNames} {student.paternalSurname}. Tu sesión sigue activa.</p><button type="button" className="extra-primary" disabled={busy} onClick={()=>void start()}>{busy?"Preparando…":"Comenzar actividad"}</button><button type="button" className="extra-secondary" onClick={()=>{clearStudentSession();St(null);T("")}}>Cambiar de alumno</button></>:<><p>Inicia sesión con tu usuario y contraseña para comenzar.</p><label>Usuario<input autoComplete="username" required value={login.username} onChange={e=>L({...login,username:e.target.value})}/></label><label>Contraseña<input autoComplete="current-password" type="password" required value={login.password} onChange={e=>L({...login,password:e.target.value})}/></label><button className="extra-primary" disabled={busy}>Comenzar</button></>}{notice&&<p role="status">{notice}</p>}</form></main>;
 if(screen==="play")return <main className="extra-page"><FocusBlurGuard enabled={activity.blurWhenInactive===true} active={screen==="play"}/><header className="extra-playbar"><a href="./">Aula en juego</a><b>{activity.timerMode==="none"?"Sin límite":activity.timerMode==="down"?fmt(remaining||0):fmt(elapsed)}</b><span>{attempts===null?"Intentos ilimitados":"Intentos restantes: "+attempts}</span></header><section className="extra-play"><div className="extra-play-title"><span className="extra-kicker">{typeTitle.toUpperCase()}</span><h1>{activity.title}</h1><p>{activity.instructions}</p><div className="extra-progress">{kind==="roulette"?"Retos completados: ":kind==="complete-phrase"?"Frases completadas: ":"Palabras encontradas: "}{progress} de {total}</div></div>
 {kind==="roulette"?<div className="extra-wheel-layout"><div className="extra-wheel" style={{transform:"rotate("+rotation+"deg)"}} aria-label="Ruleta con opciones"><span>✦</span></div><div className="extra-wheel-content"><button type="button" className="extra-primary" onClick={spin} disabled={(activity.wheelEntries||[]).every(entry=>completed.includes(entry.id))}>Girar la ruleta</button>{current&&<article className="extra-challenge">{current.imageUrl&&<img src={current.imageUrl} alt=""/>}<span>Reto seleccionado</span><h2>{current.text||"Mira la imagen y realiza el reto."}</h2><button type="button" className="extra-secondary" disabled={completed.includes(current.id)} onClick={()=>{Done(value=>value.includes(current.id)?value:[...value,current.id]);N("Reto marcado como completado.")}}>{completed.includes(current.id)?"Completado ✓":"Marcar reto como completado"}</button></article>}</div></div>:<>{kind==="complete-phrase"&&(()=>{const next=(activity.sentences||[]).find(sentence=>!found.includes(sentence.answer));return <div className="phrase-prompt"><span>Completa la frase</span><p>{next?next.before+" ____ "+next.after:"¡Completaste todas las frases!"}</p>{next&&(next.imageData||next.imageUrl)&&<img className="phrase-prompt-image" src={next.imageData||next.imageUrl||""} alt="Apoyo visual"/>}</div>})()}<div className="extra-word-wrap" key={gridVersion} onPointerMove={pointerMoveGrid} onPointerUp={pointerEnd} onPointerCancel={pointerEnd}><div className="extra-word-grid" style={{gridTemplateColumns:"repeat("+gridSize+", minmax(0, 1fr))"}}>{grid.flat().map(cell=><button type="button" key={cell.row+"-"+cell.col} className={"extra-letter"+((selected?.row===cell.row&&selected?.col===cell.col)||dragPath.some(point=>point.row===cell.row&&point.col===cell.col)?" selected":"")} data-letter-cell="1" data-row={cell.row} data-col={cell.col} aria-label={"Fila "+(cell.row+1)+", columna "+(cell.col+1)+", "+cell.letter} onPointerDown={event=>pointerStart(event,cell)} onClick={()=>{if(skipClick.current){skipClick.current=false;return}chooseCell(cell)}}>{cell.letter}</button>)}</div></div>{kind==="word-search"&&<div className="extra-word-list"><h2>Palabras</h2>{wordList.map(word=><span key={word} className={found.includes(word)?"found":""}>{kind==="word-search"&&activity.wordSearchShowClues?(activity.wordSearchClues?.[word]||word):word}</span>)}</div>}<p className="extra-hint">Arrastra desde la primera letra hasta la última. También puedes tocar el inicio y el final.</p></>}
 {notice&&screen==="play"&&<p role="status" className="extra-notice">{notice}</p>}<button className="extra-primary extra-finish" disabled={busy} onClick={()=>void finish()}>{busy?"Guardando…":"Terminar y ver resultado"}</button></section></main>;
 if(screen==="result")return <main className="extra-page"><section className="extra-result"><span className="extra-kicker">RESULTADO</span><h1>{result?.timedOut?"Se acabó el tiempo":"Actividad terminada"}</h1><strong>{result?.correct||0}/{result?.total||total}</strong><p>{kind==="roulette"?"Retos completados":kind==="complete-phrase"?"Frases completadas":"Palabras encontradas"} · Calificación: {result?.grade||0} / 10</p><p>Tiempo realizado: {fmt(result?.elapsedSeconds||elapsed)}</p><p>{result?.attemptsRemaining===null?"Puedes volver a jugar.":"Te quedan "+(result?.attemptsRemaining||0)+" intentos."}</p>{result&&(result.attemptsRemaining===null||result.attemptsRemaining>0)&&<button className="extra-primary" onClick={()=>{S("login");Res(null)}}>Intentar de nuevo</button>}{activity.showAnswersAtEnd&&<ActivityAnswerKey activity={activity}/ >}{activity.showLeaderboard&&<ActivityLeaderboard rows={leaderboard}/>}<a href="?panel=actividades">Volver a Mis actividades</a></section></main>;
 return <main className="extra-page" aria-live="polite"><section className="extra-login"><h1>Abriendo actividad…</h1><p>Espera mientras cargamos el contenido.</p></section></main>;
}
