import { useEffect, useMemo, useRef, useState } from "react";
import type { Activity, WheelEntry } from "./default-activity";
import { apiRequest, supportsActivityKind } from "./gas-client";
import "./extra-game.css";

type Kind = "roulette" | "word-search" | "complete-phrase";
type Student = { paternalSurname: string; maternalSurname: string; givenNames: string };
type Result = { correct:number; total:number; grade:number; elapsedSeconds:number; remainingSeconds:number|null; timedOut:boolean; attemptsRemaining:number|null };
type Cell = { letter:string; row:number; col:number };
const uid=()=>crypto.randomUUID();
const blank=(kind:Kind):Activity=>({id:"",kind,title:"",instructions:kind==="roulette"?"Gira la rueda y completa el reto que salga.":kind==="complete-phrase"?"Completa cada frase seleccionando sus letras en la cuadrícula.":"Encuentra todas las palabras en la cuadrícula.",timerMode:"none",timeLimitSeconds:180,maxAttempts:3,imageUrl:"",labels:[],shuffle:true,sound:true,scoring:true,wheelEntries:kind==="roulette"?[{id:uid(),text:""},{id:uid(),text:""}]:[],wordSearchWords:kind==="word-search"?["","",""]:[],wordSearchGridSize:10,phraseGridSize:10,wordSearchDirections:["horizontal","vertical","diagonal"],sentences:kind==="complete-phrase"?[{id:uid(),before:"",answer:"",after:""}]:[]});
const fmt=(n:number)=>{const v=Math.max(0,Math.floor(n));return Math.floor(v/60)+":"+String(v%60).padStart(2,"0")};
const normalize=(value:string)=>value.toLocaleUpperCase("es-MX").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-ZÑ]/g,"");
const shuffle=<T,>(items:T[])=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
function playTone(kind:Kind,enabled:boolean){if(!enabled)return;try{const context=new AudioContext(),osc=context.createOscillator(),gain=context.createGain();osc.frequency.value=kind==="roulette"?480:660;gain.gain.value=.035;osc.connect(gain);gain.connect(context.destination);osc.start();osc.stop(context.currentTime+.12);osc.onended=()=>void context.close()}catch{}}
function buildGrid(words:string[],size:number):{grid:Cell[][];placements:Array<{word:string;cells:Array<{row:number;col:number}>}>}{
 const dirs=[[0,1],[1,0],[1,1],[1,-1],[-1,1],[-1,0],[0,-1],[-1,-1]];
 const normalized=words.map(word=>({word,letters:normalize(word)})).filter(x=>x.letters);
 for(let attempt=0;attempt<100;attempt++){
  const cells=Array.from({length:size},()=>Array.from({length:size},()=> ""));
  const placements:Array<{word:string;cells:Array<{row:number;col:number}>}>=[];
  let failed=false;
  for(const item of [...normalized].sort((a,b)=>b.letters.length-a.letters.length)){
   let placed=false;
   for(let tries=0;tries<300&&!placed;tries++){
    const [dr,dc]=dirs[Math.floor(Math.random()*dirs.length)],r=Math.floor(Math.random()*size),c=Math.floor(Math.random()*size);
    const endR=r+dr*(item.letters.length-1),endC=c+dc*(item.letters.length-1);
    if(endR<0||endR>=size||endC<0||endC>=size)continue;
    const coords=Array.from({length:item.letters.length},(_,i)=>({row:r+dr*i,col:c+dc*i}));
    if(coords.some((p,i)=>cells[p.row][p.col]&&cells[p.row][p.col]!==item.letters[i]))continue;
    coords.forEach((p,i)=>cells[p.row][p.col]=item.letters[i]);
    placements.push({word:item.word,cells:coords});placed=true;
   }
   if(!placed){failed=true;break}
  }
  if(!failed){
   const letters="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
   return {grid:cells.map((row,r)=>row.map((letter,col)=>({letter:letter||letters[Math.floor(Math.random()*letters.length)],row:r,col}))),placements};
  }
 }
 throw new Error("No se pudo crear la cuadrícula. Reduce las palabras o aumenta su tamaño.");
}
export default function ExtraGame({kind}:{kind:Kind}){
 const typeTitle=kind==="roulette"?"Rueda giratoria":kind==="complete-phrase"?"Completar la frase":"Sopa de letras";
 const [screen,S]=useState("loading"),[activity,A]=useState<Activity>(()=>blank(kind)),[draft,D]=useState<Activity>(()=>blank(kind)),[saved,Sa]=useState<Activity[]>([]);
 const [key,K]=useState(sessionStorage.getItem("platformTeacherKey")||""),[keyDraft,KD]=useState("");
 const [student,St]=useState<Student|null>(null),[token,T]=useState(""),[login,L]=useState({username:"",password:""});
 const [busy,B]=useState(false),[notice,N]=useState(""),[elapsed,E]=useState(0),[remaining,R]=useState<number|null>(null),[timedOut,TO]=useState(false),[attempts,At]=useState<number|null>(null),[result,Res]=useState<Result|null>(null);
 const [current,C]=useState<WheelEntry|null>(null),[completed,Done]=useState<string[]>([]),[grid,G]=useState<Cell[][]>([]),[found,F]=useState<string[]>([]),[selected,Sel]=useState<{row:number;col:number}|null>(null);
 const [rotation,Rot]=useState(0),[gridVersion,GV]=useState(0);
 const [dragPath,DragPath]=useState<Array<{row:number;col:number}>>([]);
 const dragOrigin=useRef<Cell|null>(null),priorSelected=useRef<{row:number;col:number}|null>(null),dragging=useRef(false),skipClick=useRef(false);
 const entries=draft.wheelEntries||[];
 const wordList=kind==="complete-phrase"?(activity.sentences||[]).map(sentence=>sentence.answer):activity.wordSearchWords||[];
 const gridSize=Math.min(15,Math.max(10,Number(kind==="complete-phrase"?activity.phraseGridSize:activity.wordSearchGridSize)||10));
 const total=kind==="roulette"?(activity.wheelEntries||[]).length:kind==="complete-phrase"?(activity.sentences||[]).length:wordList.length;
 const title=activity.title||typeTitle;
 const progress=useMemo(()=>kind==="roulette"?completed.length:found.length,[kind,completed,found]);

 async function list(accessKey:string){const response=await apiRequest("/api/teacher/activities",{headers:{"x-teacher-key":accessKey}}),data=await response.json();if(!response.ok||!Array.isArray(data))throw Error(data.error||"No se pudieron cargar las actividades.");const filtered=(data as Activity[]).filter(item=>item.kind===kind);Sa(filtered);return filtered}
 async function open(id:string){const response=await apiRequest("/api/activity?id="+encodeURIComponent(id)),data=await response.json();if(!response.ok)throw Error(data.error||"No se encontró la actividad.");A(data);D(data);return data as Activity}
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get("modo")==="maestro"){const accessKey=sessionStorage.getItem("platformTeacherKey")||"";if(!accessKey){S("teacher-key");return}K(accessKey);void supportsActivityKind(kind).then(ok=>{if(!ok){N("Actualiza el Apps Script existente con el archivo Code.gs de la plataforma.");S("unsupported");return false}return true}).then(ok=>ok?list(accessKey):null).then(async rows=>{if(!rows)return;if(q.get("actividad"))await open(q.get("actividad")!);else if(q.get("nueva")==="1"){A(blank(kind));D(blank(kind))}S("teacher")}).catch(error=>{N(error instanceof Error?error.message:"No se pudo abrir el editor.");S("teacher-key")});return}const id=q.get("actividad");if(id)void open(id).then(()=>S("login")).catch(error=>{N(error instanceof Error?error.message:"No se pudo abrir la actividad.");S("login")});else S("teacher-key")},[]);
 useEffect(()=>{if(screen!=="play")return;const timer=window.setInterval(()=>{E(value=>value+1);if(activity.timerMode==="down")R(value=>{if(value===null)return null;if(value<=1){TO(true);return 0}return value-1})},1000);return()=>window.clearInterval(timer)},[screen,activity.timerMode]);
 useEffect(()=>{if(timedOut&&screen==="play")void finish(true)},[timedOut,screen]);
 async function enterTeacher(event:React.FormEvent){event.preventDefault();B(true);N("");try{if(!await supportsActivityKind(kind))throw Error("Actualiza primero el Apps Script existente con el archivo Code.gs de la plataforma.");await list(keyDraft);K(keyDraft);["platformTeacherKey","diagramTeacherKey","pairTeacherKey"].forEach(name=>sessionStorage.setItem(name,keyDraft));const q=new URLSearchParams(location.search);if(q.get("actividad"))await open(q.get("actividad")!);S("teacher")}catch(error){N(error instanceof Error?error.message:"No se pudo validar la clave.");}finally{B(false)}}
 function updateEntry(id:string,patch:Partial<WheelEntry>){D(value=>({...value,wheelEntries:(value.wheelEntries||[]).map(entry=>entry.id===id?{...entry,...patch}:entry)}))}
 function uploadEntry(id:string,file?:File){if(!file)return;if(file.size>5*1024*1024||!/^image\/(png|jpeg|webp)$/.test(file.type)){N("Usa una imagen PNG, JPG o WebP de menos de 5 MB.");return}const reader=new FileReader();reader.onload=()=>updateEntry(id,{imageData:String(reader.result),imageUrl:""});reader.readAsDataURL(file)}
 async function save(event:React.FormEvent){event.preventDefault();B(true);N("");try{if(kind==="roulette"&&(entries.length<2||entries.some(e=>!e.text.trim()&&!e.imageUrl&&!e.imageData)))throw Error("Agrega al menos dos opciones con texto o imagen.");if(kind==="word-search"){const words=(draft.wordSearchWords||[]).map(x=>x.trim()).filter(Boolean),size=Number(draft.wordSearchGridSize)||10;if(words.length<3)throw Error("Agrega al menos tres palabras.");if(words.some(word=>normalize(word).length>size))throw Error("Una palabra no cabe en la cuadrícula. Aumenta el tamaño o acórtala.");if(new Set(words.map(normalize)).size!==words.length)throw Error("No repitas palabras.");D(value=>({...value,wordSearchWords:words}))}if(kind==="complete-phrase"){const sentences=draft.sentences||[],size=Number(draft.phraseGridSize)||10;if(sentences.length<1||sentences.some(sentence=>!sentence.before.trim()||!sentence.answer.trim()))throw Error("Cada frase necesita una pista y una respuesta.");if(sentences.some(sentence=>normalize(sentence.answer).length>size))throw Error("La respuesta más larga no cabe en la cuadrícula elegida.");if(new Set(sentences.map(sentence=>normalize(sentence.answer))).size!==sentences.length)throw Error("Cada respuesta debe ser diferente para reconocerla en la cuadrícula.")}
  const payload={...draft,id:draft.id||"actividad-"+uid(),kind,labels:[],pairs:[]};
  const response=await apiRequest("/api/teacher/activity",{method:"POST",headers:{"x-teacher-key":key},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Error(data.error||"No se pudo guardar la actividad.");A(data);D(data);await list(key);N("Actividad guardada.")}catch(error){N(error instanceof Error?error.message:"No se pudo guardar.")}finally{B(false)}}
 async function loginStudent(event:React.FormEvent){event.preventDefault();B(true);N("");try{const response=await apiRequest("/api/student/login",{method:"POST",body:JSON.stringify(login)}),data=await response.json();if(!response.ok)throw Error(data.error||"Usuario o contraseña incorrectos.");St(data.student);T(data.token);await start(data.student,data.token)}catch(error){N(error instanceof Error?error.message:"No se pudo iniciar sesión.")}finally{B(false)}}
 async function start(profile:Student|null=student,tokenValue=token){if(!activity.id||!profile||!tokenValue)return;B(true);N("");try{const q=new URLSearchParams({activityId:activity.id,studentToken:tokenValue,paternalSurname:profile.paternalSurname,maternalSurname:profile.maternalSurname,givenNames:profile.givenNames}),response=await apiRequest("/api/attempts?"+q),data=await response.json();if(!response.ok||!data.canStart)throw Error(data.error||"Ya utilizaste todos tus intentos.");At(data.remaining===null?null:Number(data.remaining));E(0);R(activity.timerMode==="down"?activity.timeLimitSeconds:null);TO(false);Res(null);Done([]);F([]);C(null);Sel(null);
  if(kind==="word-search"||kind==="complete-phrase"){try{const targets=kind==="complete-phrase"?(activity.sentences||[]).map(sentence=>sentence.answer):activity.wordSearchWords||[];const made=buildGrid(targets,gridSize);G(made.grid);GV(value=>value+1)}catch(error){throw Error(error instanceof Error?error.message:"No se pudo preparar la cuadrícula.")}}
  S("play")}catch(error){N(error instanceof Error?error.message:"No se pudo comenzar.")}finally{B(false)}}
 async function finish(expired=false){if(!activity.id||!student||busy)return;B(true);N("");try{const answers=kind==="roulette"?{completedIds:completed}:kind==="complete-phrase"?Object.fromEntries((activity.sentences||[]).map(sentence=>[sentence.id,found.includes(sentence.answer)?sentence.answer:""])):{foundWords:found};const response=await apiRequest("/api/submit",{method:"POST",body:JSON.stringify({activityId:activity.id,studentToken:token,paternalSurname:student.paternalSurname,maternalSurname:student.maternalSurname,givenNames:student.givenNames,answers,elapsedSeconds:elapsed,remainingSeconds:activity.timerMode==="down"?Math.max(0,activity.timeLimitSeconds-elapsed):null,timedOut:expired||timedOut})}),data=await response.json();if(!response.ok)throw Error(data.error||"No se pudo registrar el resultado.");Res(data);At(data.attemptsRemaining===null?null:Number(data.attemptsRemaining));S("result")}catch(error){N(error instanceof Error?error.message:"No se pudo calificar.");TO(false)}finally{B(false)}}
 function spin(){const pool=(activity.wheelEntries||[]).filter(entry=>!completed.includes(entry.id));if(!pool.length){N("Ya recorriste todos los retos.");return}const choice=pool[Math.floor(Math.random()*pool.length)];C(choice);Rot(value=>value+1080+Math.floor(Math.random()*360));playTone(kind,activity.sound!==false)}
 function checkPath(start:{row:number;col:number},end:{row:number;col:number}){const dr=end.row-start.row,dc=end.col-start.col,len=Math.max(Math.abs(dr),Math.abs(dc))+1;if(!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc))){N("Selecciona letras en línea recta.");Sel(null);return}
  const stepR=Math.sign(dr),stepC=Math.sign(dc),letters:string[]=[];for(let i=0;i<len;i++)letters.push(grid[start.row+stepR*i]?.[start.col+stepC*i]?.letter||"");
  const candidate=letters.join(""),reverse=[...letters].reverse().join("");const match=wordList.find(word=>!found.includes(word)&&[candidate,reverse].includes(normalize(word)));
  if(match){F(value=>[...value,match]);playTone(kind,activity.sound!==false);N("¡Encontraste "+match+"!")}else N("Esa línea no forma una palabra de la lista.");
  Sel(null);DragPath([])}
 function chooseCell(cell:Cell){if(!selected){Sel({row:cell.row,col:cell.col});return}checkPath(selected,cell)}
 function pointerMoveGrid(event:React.PointerEvent<HTMLDivElement>){if(!dragging.current)return;const element=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>("[data-letter-cell]");if(!element)return;const row=Number(element.dataset.row),col=Number(element.dataset.col),origin=dragOrigin.current;if(!origin)return;const dr=row-origin.row,dc=col-origin.col;if(!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc)))return;const length=Math.max(Math.abs(dr),Math.abs(dc))+1,stepR=Math.sign(dr),stepC=Math.sign(dc);DragPath(Array.from({length},(_,index)=>({row:origin.row+stepR*index,col:origin.col+stepC*index})))}
 function pointerStart(event:React.PointerEvent<HTMLButtonElement>,cell:Cell){dragOrigin.current=cell;priorSelected.current=selected;dragging.current=true;skipClick.current=true;Sel({row:cell.row,col:cell.col});DragPath([{row:cell.row,col:cell.col}]);event.preventDefault()}
 function pointerEnd(event:React.PointerEvent<HTMLDivElement>){if(!dragging.current)return;dragging.current=false;const origin=dragOrigin.current;const element=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>("[data-letter-cell]");if(origin&&element){const end={row:Number(element.dataset.row),col:Number(element.dataset.col)};if(end.row!==origin.row||end.col!==origin.col)checkPath(origin,end);else if(priorSelected.current)checkPath(priorSelected.current,end);else{Sel(origin);DragPath([])}}else Sel(null);window.setTimeout(()=>{skipClick.current=false},0)}
 async function copyShare(){const link=location.origin+location.pathname+"?juego="+kind+"&actividad="+activity.id;try{await navigator.clipboard.writeText(link);N("Enlace copiado.")}catch{window.prompt("Copia el enlace para tus alumnos:",link)}}
 if(screen==="unsupported")return <main className="extra-page"><section className="extra-login"><span className="extra-kicker">PLANTILLA EN PREPARACIÓN</span><h1>{typeTitle}</h1><p>{notice}</p><a href="?panel=actividades">Volver a Mis actividades</a></section></main>;
 if(screen==="teacher-key")return <main className="extra-page"><header><a href="?panel=actividades">Mis actividades</a><b>{typeTitle}</b></header><form className="extra-login" onSubmit={enterTeacher}><span className="extra-kicker">EDITOR DE ACTIVIDAD</span><h1>Acceso del maestro</h1><label>Clave del maestro<input type="password" value={keyDraft} onChange={e=>KD(e.target.value)} required/></label>{notice&&<p role="status">{notice}</p>}<button className="extra-primary">Continuar</button></form></main>;
 if(screen==="teacher")return <main className="extra-page"><header><a href="?panel=actividades">Mis actividades</a><b>{typeTitle}</b></header><section className="extra-editor"><div className="extra-editor-head"><div><span className="extra-kicker">CREA Y EDITA</span><h1>{draft.title||"Nueva actividad"}</h1></div>{activity.id&&<button type="button" className="extra-secondary" onClick={()=>void copyShare()}>Compartir ↗</button>}</div><form onSubmit={save}><label>Título de la actividad<input required maxLength={120} value={draft.title} onChange={e=>D({...draft,title:e.target.value})}/></label><label>Instrucciones<input maxLength={240} value={draft.instructions} onChange={e=>D({...draft,instructions:e.target.value})}/></label>
 {kind==="roulette"&&<section><div className="extra-section-head"><div><h2>Opciones de la ruleta</h2><p>Cada giro elige un reto diferente hasta recorrerlos todos.</p></div><button type="button" className="extra-secondary" onClick={()=>D({...draft,wheelEntries:[...entries,{id:uid(),text:""}]})}>＋ Agregar opción</button></div>{entries.map((entry,index)=><article className="extra-row" key={entry.id}><b>{index+1}</b><label>Texto o reto<input value={entry.text} onChange={e=>updateEntry(entry.id,{text:e.target.value})} placeholder="Escribe una pregunta, tema o reto"/></label><label className="extra-upload">Imagen opcional<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadEntry(entry.id,e.target.files?.[0])}/>{(entry.imageData||entry.imageUrl)&&<img src={entry.imageData||entry.imageUrl||""} alt="Vista previa"/>}</label><button type="button" className="extra-remove" disabled={entries.length<=2} onClick={()=>D({...draft,wheelEntries:entries.filter(item=>item.id!==entry.id)})}>Quitar</button></article>)}</section>}
 {kind==="word-search"&&<section><h2>Palabras para buscar</h2><p>Se aceptan espacios y acentos; la cuadrícula muestra las letras juntas.</p>{(draft.wordSearchWords||[]).map((word,index)=><label className="extra-word-field" key={index}>Palabra {index+1}<span><input maxLength={30} value={word} onChange={e=>D({...draft,wordSearchWords:(draft.wordSearchWords||[]).map((x,i)=>i===index?e.target.value:x)})} placeholder="Ej. sistema solar"/><button type="button" className="extra-remove" disabled={(draft.wordSearchWords||[]).length<=3} onClick={()=>D({...draft,wordSearchWords:(draft.wordSearchWords||[]).filter((_,i)=>i!==index)})}>Quitar</button></span></label>)}<button type="button" className="extra-secondary" disabled={(draft.wordSearchWords||[]).length>=20} onClick={()=>D({...draft,wordSearchWords:[...(draft.wordSearchWords||[]),""]})}>＋ Agregar palabra</button><label>Tamaño de cuadrícula<select value={draft.wordSearchGridSize||10} onChange={e=>D({...draft,wordSearchGridSize:Number(e.target.value)})}>{[10,11,12,13,14,15].map(size=><option key={size} value={size}>{size} × {size}</option>)}</select></label></section>}
 {kind==="complete-phrase"&&<section><h2>Frases y respuestas</h2><p>La respuesta se esconderá en la cuadrícula de letras. El alumno la seleccionará arrastrando.</p>{(draft.sentences||[]).map((sentence,index)=><article className="extra-row phrase-edit-row" key={sentence.id}><b>{index+1}</b><label>Frase antes del espacio<input value={sentence.before} onChange={e=>D({...draft,sentences:draft.sentences!.map(item=>item.id===sentence.id?{...item,before:e.target.value}:item)})} placeholder="Ej. El planeta rojo es"/></label><label>Respuesta<input value={sentence.answer} onChange={e=>D({...draft,sentences:draft.sentences!.map(item=>item.id===sentence.id?{...item,answer:e.target.value}:item)})} placeholder="Marte"/></label><label>Texto después (opcional)<input value={sentence.after} onChange={e=>D({...draft,sentences:draft.sentences!.map(item=>item.id===sentence.id?{...item,after:e.target.value}:item)})}/></label><button type="button" className="extra-remove" disabled={(draft.sentences||[]).length<=1} onClick={()=>D({...draft,sentences:draft.sentences!.filter(item=>item.id!==sentence.id)})}>Quitar</button></article>)}<button type="button" className="extra-secondary" onClick={()=>D({...draft,sentences:[...(draft.sentences||[]),{id:uid(),before:"",answer:"",after:""}]})}>＋ Añadir frase</button><label className="phrase-grid-size">Tamaño de cuadrícula<select value={draft.phraseGridSize||10} onChange={e=>D({...draft,phraseGridSize:Number(e.target.value)})}>{[10,11,12,13,14,15].map(size=><option key={size} value={size}>{size} × {size}</option>)}</select></label></section>}
 <section className="extra-settings"><h2>Opciones del juego</h2><label>Tiempo<select value={draft.timerMode} onChange={e=>D({...draft,timerMode:e.target.value as Activity["timerMode"]})}><option value="none">Sin límite</option><option value="up">Contar el tiempo</option><option value="down">Cuenta regresiva</option></select></label>{draft.timerMode==="down"&&<label>Minutos<input type="number" min={1} max={60} value={draft.timeLimitSeconds/60} onChange={e=>D({...draft,timeLimitSeconds:Number(e.target.value)*60})}/></label>}<label>Intentos<select value={draft.maxAttempts===null?"infinite":draft.maxAttempts} onChange={e=>D({...draft,maxAttempts:e.target.value==="infinite"?null:Number(e.target.value)})}><option value="infinite">Ilimitados</option>{[1,2,3,4,5,6,7,8,9,10].map(n=><option key={n}>{n}</option>)}</select></label><label className="extra-check"><input type="checkbox" checked={draft.shuffle!==false} onChange={e=>D({...draft,shuffle:e.target.checked})}/> Mezclar aleatoriamente</label><label className="extra-check"><input type="checkbox" checked={draft.sound!==false} onChange={e=>D({...draft,sound:e.target.checked})}/> Sonidos</label></section>{notice&&<p role="status">{notice}</p>}<button className="extra-primary" disabled={busy}>{busy?"Guardando…":"Guardar actividad"}</button></form></section></main>;
 if(screen==="login")return <main className="extra-page"><form className="extra-login" onSubmit={loginStudent}><span className="extra-kicker">{typeTitle.toUpperCase()}</span><h1>{activity.title}</h1><p>Inicia sesión con tu usuario y contraseña para comenzar.</p><label>Usuario<input autoComplete="username" required value={login.username} onChange={e=>L({...login,username:e.target.value})}/></label><label>Contraseña<input autoComplete="current-password" type="password" required value={login.password} onChange={e=>L({...login,password:e.target.value})}/></label>{notice&&<p role="status">{notice}</p>}<button className="extra-primary" disabled={busy}>Comenzar</button></form></main>;
 if(screen==="play")return <main className="extra-page"><header className="extra-playbar"><a href="./">Aula en juego</a><b>{activity.timerMode==="none"?"Sin límite":activity.timerMode==="down"?fmt(remaining||0):fmt(elapsed)}</b><span>{attempts===null?"Intentos ilimitados":"Intentos restantes: "+attempts}</span></header><section className="extra-play"><div className="extra-play-title"><span className="extra-kicker">{typeTitle.toUpperCase()}</span><h1>{activity.title}</h1><p>{activity.instructions}</p><div className="extra-progress">{kind==="roulette"?"Retos completados: ":kind==="complete-phrase"?"Frases completadas: ":"Palabras encontradas: "}{progress} de {total}</div></div>
 {kind==="roulette"?<div className="extra-wheel-layout"><div className="extra-wheel" style={{transform:"rotate("+rotation+"deg)"}} aria-label="Ruleta con opciones"><span>✦</span></div><div className="extra-wheel-content"><button type="button" className="extra-primary" onClick={spin} disabled={(activity.wheelEntries||[]).every(entry=>completed.includes(entry.id))}>Girar la ruleta</button>{current&&<article className="extra-challenge">{current.imageUrl&&<img src={current.imageUrl} alt=""/>}<span>Reto seleccionado</span><h2>{current.text||"Mira la imagen y realiza el reto."}</h2><button type="button" className="extra-secondary" disabled={completed.includes(current.id)} onClick={()=>{Done(value=>value.includes(current.id)?value:[...value,current.id]);N("Reto marcado como completado.")}}>{completed.includes(current.id)?"Completado ✓":"Marcar reto como completado"}</button></article>}</div></div>:<>{kind==="complete-phrase"&&(()=>{const next=(activity.sentences||[]).find(sentence=>!found.includes(sentence.answer));return <div className="phrase-prompt"><span>Completa la frase</span><p>{next?next.before+" ____ "+next.after:"¡Completaste todas las frases!"}</p></div>})()}<div className="extra-word-wrap" key={gridVersion} onPointerMove={pointerMoveGrid} onPointerUp={pointerEnd} onPointerCancel={pointerEnd}><div className="extra-word-grid" style={{gridTemplateColumns:"repeat("+gridSize+", minmax(0, 1fr))"}}>{grid.flat().map(cell=><button type="button" key={cell.row+"-"+cell.col} className={"extra-letter"+((selected?.row===cell.row&&selected?.col===cell.col)||dragPath.some(point=>point.row===cell.row&&point.col===cell.col)?" selected":"")} data-letter-cell="1" data-row={cell.row} data-col={cell.col} aria-label={"Fila "+(cell.row+1)+", columna "+(cell.col+1)+", "+cell.letter} onPointerDown={event=>pointerStart(event,cell)} onClick={()=>{if(skipClick.current){skipClick.current=false;return}chooseCell(cell)}}>{cell.letter}</button>)}</div></div>{kind==="word-search"&&<div className="extra-word-list"><h2>Palabras</h2>{wordList.map(word=><span key={word} className={found.includes(word)?"found":""}>{word}</span>)}</div>}<p className="extra-hint">Arrastra desde la primera letra hasta la última. También puedes tocar el inicio y el final.</p></>}
 {notice&&screen==="play"&&<p role="status" className="extra-notice">{notice}</p>}<button className="extra-primary extra-finish" disabled={busy} onClick={()=>void finish()}>{busy?"Guardando…":"Terminar y ver resultado"}</button></section></main>;
 return <main className="extra-page"><section className="extra-result"><span className="extra-kicker">RESULTADO</span><h1>{result?.timedOut?"Se acabó el tiempo":"Actividad terminada"}</h1><strong>{result?.correct||0}/{result?.total||total}</strong><p>{kind==="roulette"?"Retos completados":kind==="complete-phrase"?"Frases completadas":"Palabras encontradas"} · Calificación: {result?.grade||0} / 10</p><p>Tiempo realizado: {fmt(result?.elapsedSeconds||elapsed)}</p><p>{result?.attemptsRemaining===null?"Puedes volver a jugar.":"Te quedan "+(result?.attemptsRemaining||0)+" intentos."}</p>{result&&(result.attemptsRemaining===null||result.attemptsRemaining>0)&&<button className="extra-primary" onClick={()=>{S("login");St(null);T("");Res(null)}}>Intentar de nuevo</button>}<a href="?panel=actividades">Volver a Mis actividades</a></section></main>;
}
