import { useEffect,useState } from "react";
import type { Activity } from "./default-activity";
import ActivitySettings from "./ActivitySettings";
import ActivityLeaderboard, { type LeaderboardRow } from "./ActivityLeaderboard";
import ActivityAnswerKey from "./ActivityAnswerKey";
import FocusBlurGuard from "./FocusBlurGuard";
import EditorContentHeader from "./EditorContentHeader";
import EditorImagePicker from "./EditorImagePicker";
import EditorItemActions from "./EditorItemActions";
import EditorWorkflow from "./EditorWorkflow";
import { apiRequest, forgetTeacherKey, getTeacherKey, rememberTeacherKey, supportsActivityKind, saveActivityAvailability, getStudentSession, saveStudentSession, clearStudentSession } from "./gas-client";
import "./text-game.css";
import PasswordField from "./PasswordField";

type Kind="complete-sentence"|"word-order";
type Props={kind:Kind};
type Student={paternalSurname:string;maternalSurname:string;givenNames:string};
type Sentence={id:string;before:string;answer:string;after:string;imageUrl?:string|null;imageData?:string|null};
type WordStyle={bold?:boolean;italic?:boolean;underline?:boolean};
type WordItem={id:string;text:string;bold?:boolean;italic?:boolean;underline?:boolean};
type WordSentence={id:string;text:string;imageUrl?:string|null;imageData?:string|null;wordStyles?:WordStyle[];words?:Array<WordItem&{order:number}>};
type Score={correct:number;total:number;grade:number;elapsedSeconds:number;remainingSeconds:number|null;timedOut:boolean;attemptsRemaining:number|null};
const uid=()=>crypto.randomUUID();
const blank=(kind:Kind):Activity=>({id:"",kind,title:"",instructions:kind==="complete-sentence"?"Completa cada oración con la palabra que falta.":"Ordena las palabras para formar la oración.",timerMode:"none",timeLimitSeconds:180,maxAttempts:3,imageUrl:"",labels:[],shuffle:true,sound:true,scoring:true,sentences:kind==="complete-sentence"?[{id:uid(),before:"",answer:"",after:""}]:[],wordSentences:kind==="word-order"?[{id:uid(),text:""}]:[]});
const fmt=(n:number)=>{const v=Math.max(0,Math.floor(n));return Math.floor(v/60)+":"+String(v%60).padStart(2,"0")};
const normalize=(v:string)=>v.trim().toLocaleLowerCase("es-MX").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ");
function shuffle<T>(a:T[]){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
export default function TextGame({kind}:Props){
 const previewMode=new URLSearchParams(location.search).get("vista")==="docente";
 const [screen,S]=useState("loading"),[activity,A]=useState<Activity>(()=>blank(kind)),[draft,D]=useState<Activity>(()=>blank(kind));
 const [key,K]=useState(getTeacherKey()),[keyDraft,KD]=useState(""),[saved,Sa]=useState<Activity[]>([]);
 const [student,St]=useState<Student|null>(()=>{const saved=getStudentSession()?.student;return saved?{paternalSurname:saved.paternalSurname,maternalSurname:saved.maternalSurname,givenNames:saved.givenNames}:null}),[token,T]=useState(()=>getStudentSession()?.token||""),[login,L]=useState({username:"",password:""});
 const [busy,B]=useState(false),[notice,N]=useState(""),[seconds,Sec]=useState(0),[remaining,Rem]=useState<number|null>(null),[attempts,At]=useState<number|null>(null),[timedOut,TO]=useState(false);
 const [score,Sc]=useState<Score|null>(null),[answers,Ans]=useState<Record<string,string>>({}),[wordLists,WL]=useState<Record<string,WordItem[]>>({}),[leaderboard,LB]=useState<LeaderboardRow[]>([]);
 const [selections,Selections]=useState<Record<string,{start:number;end:number}>>({});
 const title=kind==="complete-sentence"?"Completar oraciones":"Orden correcto";
 const total=kind==="complete-sentence"?activity.sentences?.length||0:activity.wordSentences?.length||0;

 async function list(keyValue:string){const r=await apiRequest("/api/teacher/activities",{headers:{"x-teacher-key":keyValue}}),data=await r.json();if(!r.ok||!Array.isArray(data))throw Error(data.error||"No se pudo verificar la clave.");const all=(data as Activity[]).filter(a=>a.kind===kind);Sa(all);return all}
 async function open(savedId:string){const r=await apiRequest("/api/activity?id="+encodeURIComponent(savedId)),data=await r.json();if(!r.ok)throw Error(data.error||"No se encontró la actividad.");A(data);D(data);return data as Activity}
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get("modo")==="maestro"){const savedKey=getTeacherKey();if(!savedKey){S("teacher-key");return}K(savedKey);const savedId=q.get("actividad");if(!savedId&&q.get("nueva")==="1"){A(blank(kind));D(blank(kind));S("teacher");void supportsActivityKind(kind).then(ok=>{if(!ok){N("El editor está listo, pero Apps Script necesita actualizarse para guardar esta plantilla.");return}return list(savedKey)}).catch(e=>N(e instanceof Error?e.message:"No se pudo actualizar la lista de actividades."));return}void supportsActivityKind(kind).then(ok=>{if(!ok){N("Actualiza el Apps Script existente con el archivo Code.gs de la plataforma.");S("unsupported");return false}return true}).then(ok=>ok?list(savedKey):null).then(async rows=>{if(!rows)return;if(savedId)await open(savedId);S("teacher")}).catch(e=>{N(e instanceof Error?e.message:"No se pudo cargar el editor.");S("teacher-error")});return}if(q.get("actividad"))void open(q.get("actividad")!).then(()=>S("login")).catch(e=>{N(e instanceof Error?e.message:"No se pudo abrir.");S("login")});else S("teacher-key")},[]);
 useEffect(()=>{if(screen!=="play")return;const t=window.setInterval(()=>{Sec(s=>s+1);if(activity.timerMode==="down")Rem(v=>{if(v===null)return null;if(v<=1){TO(true);return 0}return v-1})},1000);return()=>window.clearInterval(t)},[screen,activity.timerMode]);
 async function teacherEnter(e:React.FormEvent){e.preventDefault();B(true);N("");try{if(!await supportsActivityKind(kind)){N("Actualiza primero el Apps Script existente con el archivo Code.gs de la plataforma.");S("unsupported");return}await list(keyDraft);K(keyDraft);rememberTeacherKey(keyDraft);const q=new URLSearchParams(location.search);if(q.get("actividad"))await open(q.get("actividad")!);S("teacher")}catch(err){N(err instanceof Error?err.message:"No se pudo entrar.")}finally{B(false)}}
 async function save(e:React.FormEvent){e.preventDefault();B(true);N("");try{const payload={...draft,id:draft.id||"actividad-"+uid(),kind,labels:[],pairs:[]};if(kind==="complete-sentence"&&(!payload.sentences?.length||payload.sentences.some(x=>!x.before.trim()||!x.answer.trim())))throw Error("Completa el texto y la respuesta de cada oración.");if(kind==="word-order"&&(!payload.wordSentences?.length||payload.wordSentences.some(x=>x.text.trim().split(/\s+/).length<2)))throw Error("Cada oración debe tener al menos dos palabras.");const r=await apiRequest("/api/teacher/activity",{method:"POST",headers:{"x-teacher-key":key},body:JSON.stringify(payload)}),data=await r.json();if(!r.ok)throw Error(data.error||"No se pudo guardar.");A({...data,availableFrom:payload.availableFrom||null,availableUntil:payload.availableUntil||null});D({...data,availableFrom:payload.availableFrom||null,availableUntil:payload.availableUntil||null});await saveActivityAvailability(key,payload);window.location.assign("?panel=actividades")}catch(err){N(err instanceof Error?err.message:"No se pudo guardar.");B(false)}}
 function changeWordSentence(id:string,text:string){D(current=>({...current,wordSentences:current.wordSentences!.map(sentence=>{if(sentence.id!==id)return sentence;const oldWords=sentence.text.match(/\S+/g)||[],oldStyles=sentence.wordStyles||[],styleQueues=new Map<string,WordStyle[]>();oldWords.forEach((word,index)=>{const queue=styleQueues.get(word)||[];queue.push(oldStyles[index]||{});styleQueues.set(word,queue)});const nextStyles=(text.match(/\S+/g)||[]).map(word=>styleQueues.get(word)?.shift()||{});return {...sentence,text,wordStyles:nextStyles}})}))}
 function formatWordText(id:string,mark:keyof WordStyle){const sentence=draft.wordSentences!.find(item=>item.id===id);if(!sentence)return;const range=selections[id]||{start:0,end:sentence.text.length},selected=range.start===range.end?null:range,tokens=[...sentence.text.matchAll(/\S+/g)],affected=tokens.map(token=>{const start=token.index||0,end=start+token[0].length;return selected?start<selected.end&&end>selected.start:true}),matched=affected.map((hit,index)=>hit?index:-1).filter(index=>index>=0),turnOn=matched.some(index=>!sentence.wordStyles?.[index]?.[mark]),updated=tokens.map((_,index)=>affected[index]?{...(sentence.wordStyles?.[index]||{}),[mark]:turnOn}:{...(sentence.wordStyles?.[index]||{})});D(current=>({...current,wordSentences:current.wordSentences!.map(item=>item.id===id?{...item,wordStyles:updated}:item)}))}
 async function studentLogin(e:React.FormEvent){e.preventDefault();B(true);N("");try{const r=await apiRequest("/api/student/login",{method:"POST",body:JSON.stringify(login)}),data=await r.json();if(!r.ok)throw Error(data.error||"Usuario o contraseña incorrectos.");saveStudentSession(String(data.token),{...data.student,id:String(data.student.id)});St(data.student);T(data.token);await start(data.student,data.token)}catch(err){N(err instanceof Error?err.message:"No se pudo iniciar sesión.")}finally{B(false)}}
 async function start(profile:Student|null=student,tokenValue=token){if(!activity.id||(!previewMode&&(!profile||!tokenValue)))return;const count=kind==="complete-sentence"?(activity.sentences||[]).length:(activity.wordSentences||[]).length;if(!count){N("Esta actividad todavía no tiene contenido. El maestro debe terminar de configurarla antes de compartirla.");return}B(true);N("");try{if(!previewMode){const q=new URLSearchParams({activityId:activity.id,studentToken:tokenValue,paternalSurname:profile!.paternalSurname,maternalSurname:profile!.maternalSurname,givenNames:profile!.givenNames}),r=await apiRequest("/api/attempts?"+q),data=await r.json();if(!r.ok||!data.canStart)throw Error(data.error||"Ya no tienes intentos.");At(data.remaining===null?null:Number(data.remaining));}else At(null);Rem(activity.timerMode==="down"?activity.timeLimitSeconds:null);Sec(0);TO(false);Ans({});if(kind==="word-order"){const lists:Record<string,WordItem[]>={};(activity.wordSentences||[]).forEach(sentence=>{const tokens=sentence.words?.length?sentence.words.map(w=>({id:w.id,text:w.text,bold:w.bold,italic:w.italic,underline:w.underline})):sentence.text.trim().split(/\s+/).map((text,i)=>({id:sentence.id+"-"+i,text,...(sentence.wordStyles?.[i]||{})}));lists[sentence.id]=activity.shuffle===false?tokens:shuffle(tokens)});WL(lists)}S("play")}catch(err){N(err instanceof Error?err.message:"No se pudo iniciar.")}finally{B(false)}}
 useEffect(()=>{if(previewMode&&screen==="login"&&activity.id)void start()},[previewMode,screen,activity.id]);
 async function finish(expired=false){if(!activity.id||(!previewMode&&!student)||busy)return;B(true);N("");try{const answerData=kind==="word-order"?Object.fromEntries(Object.entries(wordLists).map(([sentenceId,words])=>[sentenceId,words.map(w=>w.id).join("|")])):answers;if(previewMode){const normalize=(v:string)=>v.trim().toLocaleLowerCase("es-MX").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ");const correct=kind==="complete-sentence"?(activity.sentences||[]).filter(x=>normalize(answers[x.id]||"")===normalize(x.answer)).length:(activity.wordSentences||[]).filter(x=>normalize((wordLists[x.id]||[]).map(w=>w.text).join(" "))===normalize(x.text)).length;Sc({correct,total,grade:total?Math.round(correct/total*100)/10:0,elapsedSeconds:seconds,remainingSeconds:activity.timerMode==="down"?Math.max(0,activity.timeLimitSeconds-seconds):null,timedOut:expired,attemptsRemaining:null});S("result");return}const r=await apiRequest("/api/submit",{method:"POST",body:JSON.stringify({activityId:activity.id,studentToken:token,paternalSurname:student!.paternalSurname,maternalSurname:student!.maternalSurname,givenNames:student!.givenNames,answers:answerData,elapsedSeconds:seconds,remainingSeconds:activity.timerMode==="down"?Math.max(0,activity.timeLimitSeconds-seconds):null,timedOut:expired||timedOut})}),data=await r.json();if(!r.ok)throw Error(data.error||"No se pudo registrar.");Sc(data);At(data.attemptsRemaining===null?null:Number(data.attemptsRemaining));if(activity.showLeaderboard){const board=await apiRequest("/api/leaderboard?activityId="+encodeURIComponent(activity.id));if(board.ok)LB(await board.json() as LeaderboardRow[])}S("result")}catch(err){N(err instanceof Error?err.message:"No se pudo calificar.");TO(false)}finally{B(false)}}
 useEffect(()=>{if(timedOut&&screen==="play")void finish(true)},[timedOut]);
 function moveWord(sentenceId:string,index:number,direction:number){const items=[...(wordLists[sentenceId]||[])],target=index+direction;if(target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];WL({...wordLists,[sentenceId]:items})}
 function moveList<T>(list:T[],index:number,offset:number){const next=[...list],to=index+offset;if(to<0||to>=next.length)return next;[next[index],next[to]]=[next[to],next[index]];return next}
 function moveListTo<T>(list:T[],from:number,to:number){const next=[...list],[item]=next.splice(from,1);next.splice(to,0,item);return next}
 if(screen==="loading")return <main className="tx-page" aria-live="polite"><section className="tx-login"><span className="tx-kicker">AULA EN JUEGO</span><h1>Abriendo {title.toLocaleLowerCase("es-MX")}</h1><p>Estamos cargando la actividad. Esto puede tardar unos segundos.</p></section></main>;
 if(screen==="teacher-error")return <main className="tx-page"><section className="tx-login"><span className="tx-kicker">NO SE PUDO CARGAR</span><h1>{title}</h1><p>{notice}</p><button className="tx-primary" onClick={()=>location.reload()}>Reintentar</button><a href="?panel=actividades">Volver a Mis actividades</a></section></main>;
 if(screen==="unsupported")return <main className="tx-page"><section className="tx-login"><span className="tx-kicker">PLANTILLA EN PREPARACIÓN</span><h1>{title}</h1><p>{notice}</p><a href="?panel=actividades">Volver a Mis actividades</a></section></main>;
 if(screen==="teacher-key")return <main className="tx-page"><header><a href="?panel=actividades">Mis actividades</a><span>{title}</span></header><form className="tx-login" onSubmit={teacherEnter}><span className="tx-kicker">EDITOR DE CONTENIDO</span><h1>Acceso del maestro</h1><label>Clave del maestro<PasswordField value={keyDraft} onChange={e=>KD(e.target.value)} required/></label>{notice&&<p>{notice}</p>}<button className="tx-primary">Continuar</button></form></main>;
 if(screen==="teacher")return <main className="tx-page"><header><a href="?panel=actividades">Mis actividades</a><span>{title}</span></header><section className="tx-editor"><EditorWorkflow template={title}/><form onSubmit={save}><EditorContentHeader title={draft.title} instructions={draft.instructions} onTitleChange={value=>D(d=>({...d,title:value}))} onInstructionsChange={value=>D(d=>({...d,instructions:value}))}/>
 {kind==="complete-sentence"&&<section><h2>Oraciones</h2>{draft.sentences!.map((sentence,index)=><article className="tx-row tx-compact-row" key={sentence.id}><header><b>Oración {index+1}</b><EditorItemActions first={index===0} last={index===draft.sentences!.length-1} index={index} onDragReorder={(from,to)=>D(d=>({...d,sentences:moveListTo(d.sentences||[],from,to)}))} deleteDisabled={draft.sentences!.length<=1} onMoveUp={()=>D(d=>({...d,sentences:moveList(d.sentences||[],index,-1)}))} onMoveDown={()=>D(d=>({...d,sentences:moveList(d.sentences||[],index,1)}))} onDuplicate={()=>{const copy={...sentence,id:uid()};D(d=>({...d,sentences:[...d.sentences!.slice(0,index+1),copy,...d.sentences!.slice(index+1)]}))}} onDelete={()=>D(d=>({...d,sentences:d.sentences!.filter(x=>x.id!==sentence.id)}))}/></header><label>Texto antes del espacio<span className="tx-control-with-image"><input value={sentence.before} onChange={e=>D(d=>({...d,sentences:d.sentences!.map(x=>x.id===sentence.id?{...x,before:e.target.value}:x)}))}/><EditorImagePicker value={sentence.imageData||sentence.imageUrl} onChange={imageData=>D(d=>({...d,sentences:d.sentences!.map(x=>x.id===sentence.id?{...x,imageData,imageUrl:""}:x)}))}/></span></label><label>Respuesta correcta<input value={sentence.answer} onChange={e=>D(d=>({...d,sentences:d.sentences!.map(x=>x.id===sentence.id?{...x,answer:e.target.value}:x)}))}/></label><label>Texto después (opcional)<input value={sentence.after} onChange={e=>D(d=>({...d,sentences:d.sentences!.map(x=>x.id===sentence.id?{...x,after:e.target.value}:x)}))}/></label></article>)}<button type="button" className="tx-secondary" onClick={()=>D({...draft,sentences:[...draft.sentences!,{id:uid(),before:"",answer:"",after:""}]})}>＋ Añadir oración</button></section>}
 {kind==="word-order"&&<section><h2>Oraciones para ordenar</h2>{draft.wordSentences!.map((sentence,index)=><article className="tx-row tx-compact-row" key={sentence.id}><header><b>Oración {index+1}</b><EditorItemActions first={index===0} last={index===draft.wordSentences!.length-1} index={index} onDragReorder={(from,to)=>D(d=>({...d,wordSentences:moveListTo(d.wordSentences||[],from,to)}))} deleteDisabled={draft.wordSentences!.length<=1} onMoveUp={()=>D(d=>({...d,wordSentences:moveList(d.wordSentences||[],index,-1)}))} onMoveDown={()=>D(d=>({...d,wordSentences:moveList(d.wordSentences||[],index,1)}))} onDuplicate={()=>{const copy={...sentence,id:uid(),wordStyles:sentence.wordStyles?.map(style=>({...style}))};D(d=>({...d,wordSentences:[...d.wordSentences!.slice(0,index+1),copy,...d.wordSentences!.slice(index+1)]}))}} onDelete={()=>D(d=>({...d,wordSentences:d.wordSentences!.filter(x=>x.id!==sentence.id)}))}/></header><label className="tx-word-editor-label">Escribe la oración completa<span className="tx-control-with-image"><textarea id={"word-order-"+sentence.id} rows={2} value={sentence.text} onSelect={e=>Selections({...selections,[sentence.id]:{start:e.currentTarget.selectionStart,end:e.currentTarget.selectionEnd}})} onChange={e=>changeWordSentence(sentence.id,e.target.value)} placeholder="Ej. El agua hierve a cien grados"/><EditorImagePicker value={sentence.imageData||sentence.imageUrl} onChange={imageData=>D(d=>({...d,wordSentences:d.wordSentences!.map(x=>x.id===sentence.id?{...x,imageData,imageUrl:""}:x)}))}/></span><span className="tx-formatbar" aria-label="Formato del texto seleccionado"><button type="button" title="Negrita" aria-label="Negrita" onMouseDown={e=>e.preventDefault()} onClick={()=>formatWordText(sentence.id,"bold")}><b>B</b></button><button type="button" title="Cursiva" aria-label="Cursiva" onMouseDown={e=>e.preventDefault()} onClick={()=>formatWordText(sentence.id,"italic")}><i>I</i></button><button type="button" title="Subrayado" aria-label="Subrayado" onMouseDown={e=>e.preventDefault()} onClick={()=>formatWordText(sentence.id,"underline")}><u>U</u></button><small>Selecciona palabras y aplica formato</small></span><span className="tx-word-format-preview" aria-label="Vista previa del formato">{(sentence.text.match(/\S+/g)||[]).map((word,wordIndex)=><span key={wordIndex} style={{fontWeight:sentence.wordStyles?.[wordIndex]?.bold?800:undefined,fontStyle:sentence.wordStyles?.[wordIndex]?.italic?"italic":undefined,textDecoration:sentence.wordStyles?.[wordIndex]?.underline?"underline":undefined}}>{word}</span>)}</span></label></article>)}<button type="button" className="tx-secondary" onClick={()=>D({...draft,wordSentences:[...draft.wordSentences!,{id:uid(),text:""}]})}>＋ Añadir oración</button></section>}
 <ActivitySettings value={draft} onChange={D}/>{notice&&<p>{notice}</p>}<button className="tx-primary" disabled={busy}>{busy?"Guardando…":"Guardar actividad"}</button>{activity.id&&<button type="button" className="tx-secondary" onClick={()=>navigator.clipboard.writeText(location.origin+location.pathname+"?juego="+kind+"&actividad="+activity.id).then(()=>N("Enlace copiado."))}>Copiar enlace para alumnos</button>}</form></section></main>;
 if(screen==="login")return <main className="tx-page"><form className="tx-login" onSubmit={studentLogin}><span className="tx-kicker">{previewMode?"VISTA PREVIA · SIN REGISTRO":title.toUpperCase()}</span><h1>{activity.title}</h1>{previewMode?<><p>Prueba el juego; tu calificación no se guardará.</p><button type="button" className="tx-primary" onClick={()=>void start()}>Probar actividad</button><a href="?panel=actividades">Volver a Mis actividades</a></>:student&&token?<><p>Hola, {student.givenNames} {student.paternalSurname}. Tu sesión sigue activa.</p><button type="button" className="tx-primary" disabled={busy} onClick={()=>void start()}>{busy?"Preparando…":"Comenzar actividad"}</button><button type="button" onClick={()=>{clearStudentSession();St(null);T("")}}>Cambiar de alumno</button></>:<><label>Usuario<input required autoComplete="username" value={login.username} onChange={e=>L({...login,username:e.target.value})}/></label><label>Contraseña<PasswordField autoComplete="current-password" required value={login.password} onChange={e=>L({...login,password:e.target.value})}/></label><button className="tx-primary" disabled={busy}>Entrar y comenzar</button></>}{notice&&<p>{notice}</p>}</form></main>;
 if(screen==="play")return <main className="tx-page"><FocusBlurGuard enabled={activity.blurWhenInactive===true} active={screen==="play"}/><header className="tx-playbar"><a href="./">Aula en juego</a><strong>{activity.timerMode==="none"?"Sin límite":activity.timerMode==="down"?fmt(remaining||0):fmt(seconds)}</strong><small>{attempts===null?"Intentos ilimitados":"Intentos restantes: "+attempts}</small></header><section className="tx-play"><span className="tx-kicker">{title.toUpperCase()}</span><h1>{activity.title}</h1><p>{activity.instructions}</p>
 {kind==="complete-sentence"&&activity.sentences?.map((sentence,index)=><article className="tx-question" key={sentence.id}>{(sentence.imageData||sentence.imageUrl)&&<img src={sentence.imageData||sentence.imageUrl||""} alt=""/>}<label><span>{index+1}. {sentence.before} <input aria-label="Respuesta faltante" value={answers[sentence.id]||""} onChange={e=>Ans({...answers,[sentence.id]:e.target.value})}/> {sentence.after}</span></label></article>)}
 {kind==="word-order"&&activity.wordSentences?.map((sentence,index)=><article className="tx-question" key={sentence.id}>{(sentence.imageData||sentence.imageUrl)&&<img src={sentence.imageData||sentence.imageUrl||""} alt=""/>}<h2>Oración {index+1}</h2><div className="tx-word-list">{(wordLists[sentence.id]||[]).map((word,i)=><span key={word.id}><b style={{fontWeight:word.bold?800:undefined,fontStyle:word.italic?"italic":undefined,textDecoration:word.underline?"underline":undefined}}>{word.text}</b><button aria-label="Mover palabra a la izquierda" disabled={i===0} onClick={()=>moveWord(sentence.id,i,-1)}>←</button><button aria-label="Mover palabra a la derecha" disabled={i===(wordLists[sentence.id]?.length||0)-1} onClick={()=>moveWord(sentence.id,i,1)}>→</button></span>)}</div></article>)}
 {notice&&<p>{notice}</p>}<button className="tx-primary tx-submit" disabled={busy} onClick={()=>void finish()}>{busy?"Guardando…":"Terminar y calificar"}</button></section></main>;
 if(screen==="result")return <main className="tx-page"><section className="tx-result"><span className="tx-kicker">{previewMode?"PRUEBA DOCENTE · NO REGISTRADA":"RESULTADO"}</span><h1>{score?.timedOut?"Se acabó el tiempo":"Actividad terminada"}</h1><strong>{score?.correct||0}/{score?.total||total}</strong><p>Calificación: {score?.grade||0} / 10</p><p>Tiempo realizado: {fmt(score?.elapsedSeconds||seconds)}</p><p>{previewMode?"El resultado solo aparece aquí; no se guardó.":score?.attemptsRemaining===null?"Puedes volver a intentarlo.":"Te quedan "+(score?.attemptsRemaining||0)+" intentos."}</p>{previewMode?<button className="tx-primary" onClick={()=>{S("login");Sc(null)}}>Probar de nuevo</button>:score&&(score.attemptsRemaining===null||score.attemptsRemaining>0)&&<button className="tx-primary" onClick={()=>{S("login");Sc(null)}}>Intentar de nuevo</button>}{!previewMode&&activity.showAnswersAtEnd&&<ActivityAnswerKey activity={activity}/ >}{!previewMode&&activity.showLeaderboard&&<ActivityLeaderboard rows={leaderboard}/ >}{previewMode&&<a href="?panel=actividades">Volver a Mis actividades</a>}</section></main>;
 return <main className="tx-page" aria-live="polite"><section className="tx-login"><h1>Abriendo actividad…</h1><p>Espera mientras cargamos el contenido.</p></section></main>;
}
