import { useEffect,useState } from "react";
import type { Activity } from "./default-activity";
import { apiRequest } from "./gas-client";
import "./text-game.css";

type Kind="complete-sentence"|"word-order";
type Props={kind:Kind};
type Student={paternalSurname:string;maternalSurname:string;givenNames:string};
type Sentence={id:string;before:string;answer:string;after:string;imageUrl?:string|null;imageData?:string|null};
type WordItem={id:string;text:string};
type WordSentence={id:string;text:string;words?:Array<WordItem&{order:number}>};
type Score={correct:number;total:number;grade:number;elapsedSeconds:number;remainingSeconds:number|null;timedOut:boolean;attemptsRemaining:number|null};
const uid=()=>crypto.randomUUID();
const blank=(kind:Kind):Activity=>({id:"",kind,title:"",instructions:kind==="complete-sentence"?"Completa cada oración con la palabra que falta.":"Ordena las palabras para formar la oración.",timerMode:"none",timeLimitSeconds:180,maxAttempts:3,imageUrl:"",labels:[],shuffle:true,sound:true,scoring:true,sentences:kind==="complete-sentence"?[{id:uid(),before:"",answer:"",after:""}]:[],wordSentences:kind==="word-order"?[{id:uid(),text:""}]:[]});
const fmt=(n:number)=>{const v=Math.max(0,Math.floor(n));return Math.floor(v/60)+":"+String(v%60).padStart(2,"0")};
const normalize=(v:string)=>v.trim().toLocaleLowerCase("es-MX").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ");
function shuffle<T>(a:T[]){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
export default function TextGame({kind}:Props){
 const [screen,S]=useState("loading"),[activity,A]=useState<Activity>(()=>blank(kind)),[draft,D]=useState<Activity>(()=>blank(kind));
 const [key,K]=useState(sessionStorage.getItem("platformTeacherKey")||""),[keyDraft,KD]=useState(""),[saved,Sa]=useState<Activity[]>([]);
 const [student,St]=useState<Student|null>(null),[token,T]=useState(""),[login,L]=useState({username:"",password:""});
 const [busy,B]=useState(false),[notice,N]=useState(""),[seconds,Sec]=useState(0),[remaining,Rem]=useState<number|null>(null),[attempts,At]=useState<number|null>(null),[timedOut,TO]=useState(false);
 const [score,Sc]=useState<Score|null>(null),[answers,Ans]=useState<Record<string,string>>({}),[wordLists,WL]=useState<Record<string,WordItem[]>>({});
 const title=kind==="complete-sentence"?"Completar oraciones":"Ordenar palabras";
 const total=kind==="complete-sentence"?activity.sentences?.length||0:activity.wordSentences?.length||0;

 async function list(keyValue:string){const r=await apiRequest("/api/teacher/activities",{headers:{"x-teacher-key":keyValue}}),data=await r.json();if(!r.ok||!Array.isArray(data))throw Error(data.error||"No se pudo verificar la clave.");const all=(data as Activity[]).filter(a=>a.kind===kind);Sa(all);return all}
 async function open(savedId:string){const r=await apiRequest("/api/activity?id="+encodeURIComponent(savedId)),data=await r.json();if(!r.ok)throw Error(data.error||"No se encontró la actividad.");A(data);D(data);return data as Activity}
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get("modo")==="maestro"){const savedKey=sessionStorage.getItem("platformTeacherKey")||"";if(!savedKey){S("teacher-key");return}K(savedKey);void list(savedKey).then(async()=>{if(q.get("actividad"))await open(q.get("actividad")!);else if(q.get("nueva")==="1"){A(blank(kind));D(blank(kind))}S("teacher")}).catch(e=>{N(e instanceof Error?e.message:"No se pudo cargar el editor.");S("teacher-key")});return}if(q.get("actividad"))void open(q.get("actividad")!).then(()=>S("login")).catch(e=>{N(e instanceof Error?e.message:"No se pudo abrir.");S("login")});else S("teacher-key")},[]);
 useEffect(()=>{if(screen!=="play")return;const t=window.setInterval(()=>{Sec(s=>s+1);if(activity.timerMode==="down")Rem(v=>{if(v===null)return null;if(v<=1){TO(true);return 0}return v-1})},1000);return()=>window.clearInterval(t)},[screen,activity.timerMode]);
 async function teacherEnter(e:React.FormEvent){e.preventDefault();B(true);N("");try{await list(keyDraft);K(keyDraft);sessionStorage.setItem("platformTeacherKey",keyDraft);sessionStorage.setItem("diagramTeacherKey",keyDraft);sessionStorage.setItem("pairTeacherKey",keyDraft);const q=new URLSearchParams(location.search);if(q.get("actividad"))await open(q.get("actividad")!);S("teacher")}catch(err){N(err instanceof Error?err.message:"No se pudo entrar.")}finally{B(false)}}
 async function save(e:React.FormEvent){e.preventDefault();B(true);N("");try{const payload={...draft,id:draft.id||"actividad-"+uid(),kind,labels:[],pairs:[]};if(kind==="complete-sentence"&&(!payload.sentences?.length||payload.sentences.some(x=>!x.before.trim()||!x.answer.trim())))throw Error("Completa el texto y la respuesta de cada oración.");if(kind==="word-order"&&(!payload.wordSentences?.length||payload.wordSentences.some(x=>x.text.trim().split(/\s+/).length<2)))throw Error("Cada oración debe tener al menos dos palabras.");const r=await apiRequest("/api/teacher/activity",{method:"POST",headers:{"x-teacher-key":key},body:JSON.stringify(payload)}),data=await r.json();if(!r.ok)throw Error(data.error||"No se pudo guardar.");A(data);D(data);await list(key);N("Actividad guardada.")}catch(err){N(err instanceof Error?err.message:"No se pudo guardar.")}finally{B(false)}}
 async function studentLogin(e:React.FormEvent){e.preventDefault();B(true);N("");try{const r=await apiRequest("/api/student/login",{method:"POST",body:JSON.stringify(login)}),data=await r.json();if(!r.ok)throw Error(data.error||"Usuario o contraseña incorrectos.");St(data.student);T(data.token);await start(data.student,data.token)}catch(err){N(err instanceof Error?err.message:"No se pudo iniciar sesión.")}finally{B(false)}}
 async function start(profile:Student|null=student,tokenValue=token){if(!activity.id||!profile||!tokenValue)return;B(true);N("");try{const q=new URLSearchParams({activityId:activity.id,studentToken:tokenValue,paternalSurname:profile.paternalSurname,maternalSurname:profile.maternalSurname,givenNames:profile.givenNames}),r=await apiRequest("/api/attempts?"+q),data=await r.json();if(!r.ok||!data.canStart)throw Error(data.error||"Ya no tienes intentos.");At(data.remaining===null?null:Number(data.remaining));Rem(activity.timerMode==="down"?activity.timeLimitSeconds:null);Sec(0);TO(false);Ans({});if(kind==="word-order"){const lists:Record<string,WordItem[]>={};(activity.wordSentences||[]).forEach(sentence=>{const tokens=sentence.words?.length?sentence.words.map(w=>({id:w.id,text:w.text})):sentence.text.trim().split(/\s+/).map((text,i)=>({id:sentence.id+"-"+i,text}));lists[sentence.id]=activity.shuffle===false?tokens:shuffle(tokens)});WL(lists)}S("play")}catch(err){N(err instanceof Error?err.message:"No se pudo iniciar.")}finally{B(false)}}
 async function finish(expired=false){if(!activity.id||!student||busy)return;B(true);N("");try{const answerData=kind==="word-order"?Object.fromEntries(Object.entries(wordLists).map(([sentenceId,words])=>[sentenceId,words.map(w=>w.id).join("|")])):answers;const r=await apiRequest("/api/submit",{method:"POST",body:JSON.stringify({activityId:activity.id,studentToken:token,paternalSurname:student.paternalSurname,maternalSurname:student.maternalSurname,givenNames:student.givenNames,answers:answerData,elapsedSeconds:seconds,remainingSeconds:activity.timerMode==="down"?Math.max(0,activity.timeLimitSeconds-seconds):null,timedOut:expired||timedOut})}),data=await r.json();if(!r.ok)throw Error(data.error||"No se pudo registrar.");Sc(data);At(data.attemptsRemaining===null?null:Number(data.attemptsRemaining));S("result")}catch(err){N(err instanceof Error?err.message:"No se pudo calificar.");TO(false)}finally{B(false)}}
 useEffect(()=>{if(timedOut&&screen==="play")void finish(true)},[timedOut]);
 function moveWord(sentenceId:string,index:number,direction:number){const items=[...(wordLists[sentenceId]||[])],target=index+direction;if(target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];WL({...wordLists,[sentenceId]:items})}
 function upload(sentenceId:string,file?:File){if(!file)return;if(file.size>5*1024*1024){N("La imagen debe pesar menos de 5 MB.");return}if(!/^image\/(png|jpeg|webp)$/.test(file.type)){N("Usa una imagen PNG, JPG o WebP.");return}const reader=new FileReader();reader.onload=()=>D({...draft,sentences:draft.sentences!.map(x=>x.id===sentenceId?{...x,imageData:String(reader.result),imageUrl:""}:x)});reader.readAsDataURL(file)}
 if(screen==="teacher-key")return <main className="tx-page"><header><a href="?panel=actividades">Mis actividades</a><span>{title}</span></header><form className="tx-login" onSubmit={teacherEnter}><span className="tx-kicker">EDITOR DE CONTENIDO</span><h1>Acceso del maestro</h1><label>Clave del maestro<input type="password" value={keyDraft} onChange={e=>KD(e.target.value)} required/></label>{notice&&<p>{notice}</p>}<button className="tx-primary">Continuar</button></form></main>;
 if(screen==="teacher")return <main className="tx-page"><header><a href="?panel=actividades">Mis actividades</a><span>{title}</span></header><section className="tx-editor"><div className="tx-head"><div><span className="tx-kicker">INTRODUCIR CONTENIDO</span><h1>{draft.title||"Nueva actividad"}</h1></div><label>Abrir guardada<select value={activity.id} onChange={e=>{const a=saved.find(x=>x.id===e.target.value);if(a){A(a);D(a)}}}><option value="">Nueva actividad</option>{saved.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label></div><form onSubmit={save}><label>Título<input required value={draft.title} onChange={e=>D({...draft,title:e.target.value})}/></label><label>Instrucciones<input value={draft.instructions} onChange={e=>D({...draft,instructions:e.target.value})}/></label>
 {kind==="complete-sentence"&&<section><h2>Oraciones</h2>{draft.sentences!.map((sentence,index)=><article className="tx-row" key={sentence.id}><b>Oración {index+1}</b><label>Texto antes del espacio<input value={sentence.before} onChange={e=>D({...draft,sentences:draft.sentences!.map(x=>x.id===sentence.id?{...x,before:e.target.value}:x)})}/></label><label>Respuesta correcta<input value={sentence.answer} onChange={e=>D({...draft,sentences:draft.sentences!.map(x=>x.id===sentence.id?{...x,answer:e.target.value}:x)})}/></label><label>Texto después (opcional)<input value={sentence.after} onChange={e=>D({...draft,sentences:draft.sentences!.map(x=>x.id===sentence.id?{...x,after:e.target.value}:x)})}/></label><label>Imagen opcional<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(sentence.id,e.target.files?.[0])}/></label><button type="button" onClick={()=>D({...draft,sentences:draft.sentences!.filter(x=>x.id!==sentence.id)})} disabled={draft.sentences!.length<=1}>Quitar oración</button></article>)}<button type="button" className="tx-secondary" onClick={()=>D({...draft,sentences:[...draft.sentences!,{id:uid(),before:"",answer:"",after:""}]})}>＋ Añadir oración</button></section>}
 {kind==="word-order"&&<section><h2>Oraciones para ordenar</h2>{draft.wordSentences!.map((sentence,index)=><article className="tx-row" key={sentence.id}><b>Oración {index+1}</b><label>Escribe la oración completa<input value={sentence.text} onChange={e=>D({...draft,wordSentences:draft.wordSentences!.map(x=>x.id===sentence.id?{...x,text:e.target.value}:x)})} placeholder="Ej. El agua hierve a cien grados"/></label><button type="button" onClick={()=>D({...draft,wordSentences:draft.wordSentences!.filter(x=>x.id!==sentence.id)})} disabled={draft.wordSentences!.length<=1}>Quitar</button></article>)}<button type="button" className="tx-secondary" onClick={()=>D({...draft,wordSentences:[...draft.wordSentences!,{id:uid(),text:""}]})}>＋ Añadir oración</button></section>}
 <section className="tx-settings"><h2>Opciones</h2><label>Tiempo<select value={draft.timerMode} onChange={e=>D({...draft,timerMode:e.target.value as Activity["timerMode"]})}><option value="none">Sin límite</option><option value="up">Contar el tiempo</option><option value="down">Cuenta regresiva</option></select></label>{draft.timerMode==="down"&&<label>Minutos<input type="number" min="1" max="60" value={draft.timeLimitSeconds/60} onChange={e=>D({...draft,timeLimitSeconds:Number(e.target.value)*60})}/></label>}<label>Intentos<select value={draft.maxAttempts===null?"infinite":draft.maxAttempts} onChange={e=>D({...draft,maxAttempts:e.target.value==="infinite"?null:Number(e.target.value)})}><option value="infinite">Ilimitados</option>{[1,2,3,4,5,6,7,8,9,10].map(n=><option key={n}>{n}</option>)}</select></label><label><input type="checkbox" checked={draft.shuffle!==false} onChange={e=>D({...draft,shuffle:e.target.checked})}/> Mezclar</label><label><input type="checkbox" checked={draft.sound!==false} onChange={e=>D({...draft,sound:e.target.checked})}/> Sonidos</label></section>{notice&&<p>{notice}</p>}<button className="tx-primary" disabled={busy}>{busy?"Guardando…":"Guardar actividad"}</button>{activity.id&&<button type="button" className="tx-secondary" onClick={()=>navigator.clipboard.writeText(location.origin+location.pathname+"?juego="+kind+"&actividad="+activity.id).then(()=>N("Enlace copiado."))}>Copiar enlace para alumnos</button>}</form></section></main>;
 if(screen==="login")return <main className="tx-page"><form className="tx-login" onSubmit={studentLogin}><span className="tx-kicker">{title.toUpperCase()}</span><h1>{activity.title}</h1><label>Usuario<input required value={login.username} onChange={e=>L({...login,username:e.target.value})}/></label><label>Contraseña<input type="password" required value={login.password} onChange={e=>L({...login,password:e.target.value})}/></label>{notice&&<p>{notice}</p>}<button className="tx-primary" disabled={busy}>Entrar y comenzar</button></form></main>;
 if(screen==="play")return <main className="tx-page"><header className="tx-playbar"><a href="./">Aula en juego</a><strong>{activity.timerMode==="none"?"Sin límite":activity.timerMode==="down"?fmt(remaining||0):fmt(seconds)}</strong><small>{attempts===null?"Intentos ilimitados":"Intentos restantes: "+attempts}</small></header><section className="tx-play"><span className="tx-kicker">{title.toUpperCase()}</span><h1>{activity.title}</h1><p>{activity.instructions}</p>
 {kind==="complete-sentence"&&activity.sentences?.map((sentence,index)=><article className="tx-question" key={sentence.id}>{sentence.imageUrl&&<img src={sentence.imageUrl} alt=""/>}<label><span>{index+1}. {sentence.before} <input aria-label="Respuesta faltante" value={answers[sentence.id]||""} onChange={e=>Ans({...answers,[sentence.id]:e.target.value})}/> {sentence.after}</span></label></article>)}
 {kind==="word-order"&&activity.wordSentences?.map((sentence,index)=><article className="tx-question" key={sentence.id}><h2>Oración {index+1}</h2><div className="tx-word-list">{(wordLists[sentence.id]||[]).map((word,i)=><span key={word.id}><b>{word.text}</b><button aria-label="Mover palabra a la izquierda" disabled={i===0} onClick={()=>moveWord(sentence.id,i,-1)}>←</button><button aria-label="Mover palabra a la derecha" disabled={i===(wordLists[sentence.id]?.length||0)-1} onClick={()=>moveWord(sentence.id,i,1)}>→</button></span>)}</div></article>)}
 {notice&&<p>{notice}</p>}<button className="tx-primary tx-submit" disabled={busy} onClick={()=>void finish()}>{busy?"Guardando…":"Terminar y calificar"}</button></section></main>;
 return <main className="tx-page"><section className="tx-result"><span className="tx-kicker">RESULTADO</span><h1>{score?.timedOut?"Se acabó el tiempo":"Actividad terminada"}</h1><strong>{score?.correct||0}/{score?.total||total}</strong><p>Calificación: {score?.grade||0} / 10</p><p>Tiempo realizado: {fmt(score?.elapsedSeconds||seconds)}</p><p>{score?.attemptsRemaining===null?"Puedes volver a intentarlo.":"Te quedan "+(score?.attemptsRemaining||0)+" intentos."}</p>{score&&(score.attemptsRemaining===null||score.attemptsRemaining>0)&&<button className="tx-primary" onClick={()=>{S("login");St(null);T("");Sc(null)}}>Intentar de nuevo</button>}</section></main>;
}
